In [2]:
import os

# Show current working directory
print("Current folder:", os.getcwd())

# List all files and folders
for item in sorted(os.listdir(".")):
    print(" ", item)

Current folder: C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops
  .github
  .gitignore
  .ipynb_checkpoints
  00_MASTER_RUNNER.ipynb
  Dockerfile
  data
  deployment
  monitoring
  notebooks
  readme.md
  requirements.txt
  screenshots
  src
  tests

In [3]:
import sys

# Install all required packages
!"{sys.executable}" -m pip install \
    pandas==2.1.0 \
    numpy==1.25.2 \
    scikit-learn==1.3.0 \
    matplotlib==3.7.2 \
    seaborn==0.12.2 \
    mlflow==2.7.1 \
    joblib==1.3.2 \
    fastapi==0.103.1 \
    uvicorn==0.23.2 \
    pydantic==2.3.0 \
    prometheus-client==0.17.1 \
    pytest==7.4.2 \
    httpx==0.25.0 \
    flake8==6.1.0

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas==2.1.0
  Downloading pandas-2.1.0.tar.gz (4.3 MB)
     ---------------------------------------- 0.0/4.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/4.3 MB ? eta -:--:--
     --------- ------------------------------ 1.0/4.3 MB 4.2 MB/s eta 0:00:01
     -------------- ------------------------- 1.6/4.3 MB 3.4 MB/s eta 0:00:01
     ----------------- ---------------------- 1.8/4.3 MB 2.8 MB/s eta 0:00:01
     ------------------- -------------------- 2.1/4.3 MB 2.2 MB/s eta 0:00:01
     ------------------- -------------------- 2.1/4.3 MB 2.2 MB/s eta 0:00:01
     ------------------- -------------------- 2.1/4.3 MB 2.2 MB/s eta 0:00:01
     ------------------- -------------------- 2.1/4.3 MB 2.2 MB/s eta 0:00:01
     ---------------------- ----------------- 2.4/4.3 MB 1.3 MB/s eta 0:00:02
     ---------------------- ----------------- 2.4/4.3 MB 1.3 MB/s eta 0:00:02
     ---------------------- ----------------- 2.4/4.3 MB 1.3 MB/s eta 0:00:02
     ---------------------- ----------------- 2.4/4.3 MB 1.3 MB/s eta 0:00:02
     ---------------------- ----------------- 2.4/4.3 MB 1.3 MB/s eta 0:00:02
     ------------------------ --------------- 2.6/4.3 MB 867.7 kB/s eta 0:00:02
     ------------------------ --------------- 2.6/4.3 MB 867.7 kB/s eta 0:00:02
     ------------------------ --------------- 2.6/4.3 MB 867.7 kB/s eta 0:00:02
     ------------------------ --------------- 2.6/4.3 MB 867.7 kB/s eta 0:00:02
     ------------------------ --------------- 2.6/4.3 MB 867.7 kB/s eta 0:00:02
     --------------------------- ------------ 2.9/4.3 MB 687.5 kB/s eta 0:00:03
     --------------------------- ------------ 2.9/4.3 MB 687.5 kB/s eta 0:00:03
     --------------------------- ------------ 2.9/4.3 MB 687.5 kB/s eta 0:00:03
     --------------------------- ------------ 2.9/4.3 MB 687.5 kB/s eta 0:00:03
     ----------------------------- ---------- 3.1/4.3 MB 645.2 kB/s eta 0:00:02
     ----------------------------- ---------- 3.1/4.3 MB 645.2 kB/s eta 0:00:02
     ------------------------------- -------- 3.4/4.3 MB 621.3 kB/s eta 0:00:02
     ------------------------------- -------- 3.4/4.3 MB 621.3 kB/s eta 0:00:02
     ------------------------------- -------- 3.4/4.3 MB 621.3 kB/s eta 0:00:02
     ------------------------------- -------- 3.4/4.3 MB 621.3 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ---------------------------------- ----- 3.7/4.3 MB 578.5 kB/s eta 0:00:02
     ------------------------------------ --- 3.9/4.3 MB 491.4 kB/s eta 0:00:01
     ------------------------------------ --- 3.9/4.3 MB 491.4 kB/s eta 0:00:01
     ------------------------------------ --- 3.9/4.3 MB 491.4 kB/s eta 0:00:01
     ------------------------------------ --- 3.9/4.3 MB 491.4 kB/s eta 0:00:01
     ---------------------------------------  4.2/4.3 MB 473.0 kB/s eta 0:00:01
     ---------------------------------------- 4.3/4.3 MB 467.3 kB/s  0:00:08
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): still running...
  Preparing metadata (pyproject.toml): still running...
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 2

  [118 lines of output]
  + meson setup C:\Users\madhanma\AppData\Local\Temp\pip-install-3n95g7mn\pandas_8ea87da284d54e3783b9df7e296a0ac3 C:\Users\madhanma\AppData\Local\Temp\pip-install-3n95g7mn\pandas_8ea87da284d54e3783b9df7e296a0ac3\.mesonpy-mb4s2z94\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\madhanma\AppData\Local\Temp\pip-install-3n95g7mn\pandas_8ea87da284d54e3783b9df7e296a0ac3\.mesonpy-mb4s2z94\build\meson-python-native-file.ini
  The Meson build system
  Version: 1.0.1
  Source dir: C:\Users\madhanma\AppData\Local\Temp\pip-install-3n95g7mn\pandas_8ea87da284d54e3783b9df7e296a0ac3
  Build dir: C:\Users\madhanma\AppData\Local\Temp\pip-install-3n95g7mn\pandas_8ea87da284d54e3783b9df7e296a0ac3\.mesonpy-mb4s2z94\build
  Build type: native build
  Project name: pandas
  Project version: 2.1.0
  Activating VS 18.2.1
  C compiler for the host machine: cl (msvc 19.50.35723 "Microsoft (R) C/C++ Optimizing Compiler Version 19.50.35723 for x64")
  C linker for the host machine: link link 14.50.35723.0
  C++ compiler for the host machine: cl (msvc 19.50.35723 "Microsoft (R) C/C++ Optimizing Compiler Version 19.50.35723 for x64")
  C++ linker for the host machine: link link 14.50.35723.0
  Cython compiler for the host machine: cython (cython 0.29.37)
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (C:\ProgramData\anaconda3\python.exe)
  Build targets in project: 53

  pandas 2.1.0

    User defined options
      Native files: C:\Users\madhanma\AppData\Local\Temp\pip-install-3n95g7mn\pandas_8ea87da284d54e3783b9df7e296a0ac3\.mesonpy-mb4s2z94\build\meson-python-native-file.ini
      buildtype   : release
      b_ndebug    : if-release
      b_vscrt     : md

  Found ninja.EXE-1.13.0.git.kitware.jobserver-pipe-1 at C:\Users\madhanma\AppData\Local\Temp\pip-build-env-4cs4ey8f\normal\Scripts\ninja.EXE

  Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
  C:\Users\madhanma\AppData\Local\Temp\pip-build-env-4cs4ey8f\overlay\Scripts\meson compile -C .
  + meson compile
  [1/151] Generating pandas/_libs/algos_take_helper_pxi with a custom command
  [2/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom command
  [3/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom command
  [4/151] Generating pandas/_libs/algos_common_helper_pxi with a custom command
  [5/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom command
  [6/151] Generating pandas/_libs/index_class_helper_pxi with a custom command
  [7/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom command
  [8/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command
  [9/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/base.pyx
  [10/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/ccalendar.pyx
  [11/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/dtypes.pyx
  [12/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/np_datetime.pyx
  [13/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/nattype.pyx
  [14/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/timezones.pyx
  [15/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/arrays.pyx
  [16/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/vectorized.pyx
  [17/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/tzconversion.pyx
  [18/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/conversion.pyx
  [19/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/strptime.pyx
  [20/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/parsing.pyx
  [21/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/indexing.pyx
  [22/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/fields.pyx
  [23/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/offsets.pyx
  [24/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/period.pyx
  [25/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/timestamps.pyx
  [26/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslibs/timedeltas.pyx
  [27/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/ops_dispatch.pyx
  [28/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/hashing.pyx
  [29/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/byteswap.pyx
  [30/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/properties.pyx
  [31/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/missing.pyx
  [32/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/testing.pyx
  [33/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/internals.pyx
  [34/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/sas.pyx
  [35/151] Compiling C object pandas/_libs/tslibs/base.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_base.pyx.c.obj
  [36/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/ops.pyx
  [37/151] Compiling C object pandas/_libs/tslibs/ccalendar.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.obj
  [38/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/reshape.pyx
  [39/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/parsers.pyx
  [40/151] Compiling C object pandas/_libs/tslibs/conversion.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_conversion.pyx.c.obj
  [41/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/tslib.pyx
  [42/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/index.pyx
  [43/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/lib.pyx
  [44/151] Compiling C object pandas/_libs/tslibs/parsing.cp312-win_amd64.pyd.p/.._src_parser_tokenizer.c.obj
  [45/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/writers.pyx
  [46/151] Compiling C object pandas/_libs/tslibs/np_datetime.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_np_datetime.pyx.c.obj
  [47/151] Compiling C object pandas/_libs/tslibs/dtypes.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.obj
  [48/151] Compiling C object pandas/_libs/tslibs/fields.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_fields.pyx.c.obj
  [49/151] Compiling C object pandas/_libs/tslibs/period.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_period.pyx.c.obj
  [50/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/window/indexers.pyx
  [51/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/window/aggregations.pyx
  [52/151] Compiling C object pandas/_libs/arrays.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_arrays.pyx.c.obj
  [53/151] Compiling C object pandas/_libs/tslibs/vectorized.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_vectorized.pyx.c.obj
  [54/151] Compiling C object pandas/_libs/hashing.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_hashing.pyx.c.obj
  [55/151] Compiling C object pandas/_libs/indexing.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_indexing.pyx.c.obj
  [56/151] Compiling C object pandas/_libs/tslibs/nattype.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_nattype.pyx.c.obj
  [57/151] Compiling C object pandas/_libs/tslibs/timezones.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_timezones.pyx.c.obj
  [58/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/interval.pyx
  [59/151] Compiling C object pandas/_libs/lib.cp312-win_amd64.pyd.p/src_parser_tokenizer.c.obj
  [60/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/sparse.pyx
  [61/151] Compiling C object pandas/_libs/pandas_datetime.cp312-win_amd64.pyd.p/src_vendored_numpy_datetime_np_datetime.c.obj
  FAILED: [code=2] pandas/_libs/pandas_datetime.cp312-win_amd64.pyd.p/src_vendored_numpy_datetime_np_datetime.c.obj
  "cl" "-Ipandas\_libs\pandas_datetime.cp312-win_amd64.pyd.p" "-Ipandas\_libs" "-I..\..\pandas\_libs" "-I..\..\..\..\pip-build-env-4cs4ey8f\overlay\Lib\site-packages\numpy\_core\include" "-I..\..\pandas\_libs\include" "-IC:\ProgramData\anaconda3\Include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "-DNPY_NO_DEPRECATED_API=0" "-DNPY_TARGET_VERSION=NPY_1_21_API_VERSION" "/Fdpandas\_libs\pandas_datetime.cp312-win_amd64.pyd.p\src_vendored_numpy_datetime_np_datetime.c.pdb" /Fopandas/_libs/pandas_datetime.cp312-win_amd64.pyd.p/src_vendored_numpy_datetime_np_datetime.c.obj "/c" ../../pandas/_libs/src/vendored/numpy/datetime/np_datetime.c
  ../../pandas/_libs/src/vendored/numpy/datetime/np_datetime.c(946): error C2039: 'c_metadata': is not a member of '_PyArray_Descr'
  C:\Users\madhanma\AppData\Local\Temp\pip-build-env-4cs4ey8f\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h(654): note: see declaration of '_PyArray_Descr'
  ../../pandas/_libs/src/vendored/numpy/datetime/np_datetime.c(946): warning C4033: 'get_datetime_metadata_from_dtype' must return a value
  [62/151] Compiling C object pandas/_libs/tslibs/parsing.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_parsing.pyx.c.obj
  [63/151] Compiling C object pandas/_libs/internals.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_internals.pyx.c.obj
  [64/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/hashtable.pyx
  [65/151] Compiling C object pandas/_libs/missing.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_missing.pyx.c.obj
  [66/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/algos.pyx
  [67/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/groupby.pyx
  [68/151] Compiling C object pandas/_libs/tslibs/tzconversion.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_tzconversion.pyx.c.obj
  [69/151] Compiling C object pandas/_libs/tslibs/timedeltas.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_timedeltas.pyx.c.obj
  [70/151] Compiling C object pandas/_libs/tslibs/timestamps.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_timestamps.pyx.c.obj
  [71/151] Compiling Cython source C:/Users/madhanma/AppData/Local/Temp/pip-install-3n95g7mn/pandas_8ea87da284d54e3783b9df7e296a0ac3/pandas/_libs/join.pyx
  [72/151] Compiling C object pandas/_libs/index.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_index.pyx.c.obj
  [73/151] Compiling C object pandas/_libs/tslibs/offsets.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_offsets.pyx.c.obj
  [74/151] Compiling C object pandas/_libs/tslibs/strptime.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_tslibs_strptime.pyx.c.obj
  [75/151] Compiling C object pandas/_libs/lib.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_lib.pyx.c.obj
  [76/151] Compiling C object pandas/_libs/interval.cp312-win_amd64.pyd.p/meson-generated_pandas__libs_interval.pyx.c.obj
  ninja: build stopped: subcommand failed.
  Activating VS 18.2.1
  INFO: automatically activated MSVC compiler environment
  INFO: autodetecting backend as ninja
  INFO: calculating backend command to run: C:\Users\madhanma\AppData\Local\Temp\pip-build-env-4cs4ey8f\normal\Scripts\ninja.EXE
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: metadata-generation-failed

Encountered error while generating package metadata.

pandas

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
# Verify all critical packages are importable
packages = {
    "pandas"            : "pd",
    "numpy"             : "np",
    "sklearn"           : "sklearn",
    "matplotlib"        : "matplotlib",
    "seaborn"           : "seaborn",
    "mlflow"            : "mlflow",
    "joblib"            : "joblib",
    "fastapi"           : "fastapi",
    "uvicorn"           : "uvicorn",
    "pydantic"          : "pydantic",
    "prometheus_client" : "prometheus_client",
    "pytest"            : "pytest",
    "httpx"             : "httpx",
    "flake8"            : "flake8",
}

print("=" * 45)
print("  PACKAGE VERIFICATION")
print("=" * 45)

all_good = True
for package, alias in packages.items():
    try:
        mod = __import__(package)
        version = getattr(mod, "__version__", "unknown")
        print(f"  ✅  {package:<25} {version}")
    except ImportError as e:
        print(f"  ❌  {package:<25} MISSING — {e}")
        all_good = False

print("=" * 45)
if all_good:
    print("  🎉  All packages installed successfully!")
else:
    print("  ⚠️   Some packages are missing!")
    print("       Re-run Cell 3 for missing ones.")
print("=" * 45)

In [9]:
import sys
import os
os.environ["PYTHONIOENCODING"] = "utf-8"
# Make sure we are in the project root
print("Running from:", os.getcwd())

# Run the download script
!"{sys.executable}" data/download_data.py

Running from: C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops
[INFO] data/ directory ready.
[INFO] Downloading dataset from:
       https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data
[INFO] Raw file saved â†’ data\heart_raw.csv
[INFO] Raw shape       : (303, 14)
[INFO] Target binarized: 0 = No Disease | 1 = Disease
[INFO] Filled 'ca' â€” 4 NaN(s) replaced with median=0.0
[INFO] Filled 'thal' â€” 2 NaN(s) replaced with median=3.0
[INFO] Cleaned file saved â†’ data\heart_cleaned.csv

==================================================
  DATASET SUMMARY
==================================================
  Rows      : 303
  Columns   : 14
  Missing   : 0
  Target 0  : 164  (No Disease)
  Target 1  : 139  (Disease)
==================================================
age         float64
sex         float64
cp          float64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca          float64
thal        float64
target        int32
==================================================

[DONE] Dataset ready for EDA and training.

In [10]:
import os
import pandas as pd

# Check both files were created
files_to_check = [
    "data/heart_raw.csv",
    "data/heart_cleaned.csv",
]

print("=" * 45)
print("  DATASET FILE CHECK")
print("=" * 45)

for f in files_to_check:
    if os.path.exists(f):
        size = os.path.getsize(f)
        print(f"  ✅  {f}")
        print(f"       Size : {size:,} bytes")
    else:
        print(f"  ❌  {f} — NOT FOUND")

print("=" * 45)

=============================================
  DATASET FILE CHECK
=============================================
  ✅  data/heart_raw.csv
       Size : 18,461 bytes
  ✅  data/heart_cleaned.csv
       Size : 18,857 bytes
=============================================

In [11]:
import pandas as pd

# Load and display the cleaned dataset
df = pd.read_csv("data/heart_cleaned.csv")

print("=" * 45)
print("  DATASET PREVIEW")
print("=" * 45)
print(f"\n  Shape : {df.shape[0]} rows × {df.shape[1]} columns")
print(f"\n  Columns : {list(df.columns)}")
print(f"\n  Missing values : {df.isnull().sum().sum()}")
print(f"\n  Target distribution:")
print(f"    No Disease (0) : {(df['target']==0).sum()}")
print(f"    Disease    (1) : {(df['target']==1).sum()}")
print("\n  First 5 rows:")
display(df.head())
print("\n  Basic statistics:")
display(df.describe().round(2))

=============================================
  DATASET PREVIEW
=============================================

  Shape : 303 rows × 14 columns

  Columns : ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

  Missing values : 0

  Target distribution:
    No Disease (0) : 164
    Disease    (1) : 139

  First 5 rows:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

  Basic statistics:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00,303.00
mean,54.44,0.68,3.16,131.69,246.69,0.15,0.99,149.61,0.33,1.04,1.60,0.66,4.72,0.46
std,9.04,0.47,0.96,17.60,51.78,0.36,0.99,22.88,0.47,1.16,0.62,0.93,1.94,0.50
min,29.00,0.00,1.00,94.00,126.00,0.00,0.00,71.00,0.00,0.00,1.00,0.00,3.00,0.00
25%,48.00,0.00,3.00,120.00,211.00,0.00,0.00,133.50,0.00,0.00,1.00,0.00,3.00,0.00
50%,56.00,1.00,3.00,130.00,241.00,0.00,1.00,153.00,0.00,0.80,2.00,0.00,3.00,0.00
75%,61.00,1.00,4.00,140.00,275.00,0.00,2.00,166.00,1.00,1.60,2.00,1.00,7.00,1.00
max,77.00,1.00,4.00,200.00,564.00,1.00,2.00,202.00,1.00,6.20,3.00,3.00,7.00,1.00

#**************************************************************************************************************
MODEL TRAINING
**************************************************************************************************************#

In [29]:
import sys
import os

# Completely suppress Git requirement in MLflow
os.environ["GIT_PYTHON_REFRESH"] = "quiet"
os.environ["GIT_PYTHON_GIT_EXECUTABLE"] = "git"
print("=" * 55)
print("  STARTING MODEL TRAINING PIPELINE")
print("=" * 55)

# Run the training script
!"{sys.executable}" src/train.py

=======================================================
  STARTING MODEL TRAINING PIPELINE
=======================================================

=======================================================
  HEART DISEASE â€” MODEL TRAINING PIPELINE
=======================================================
[INFO] Data loaded from 'data\heart_cleaned.csv' â€” shape: (303, 14)
[INFO] clean_data : no missing values detected.
[INFO] split_data  : train=242, test=61 (test_size=0.2, stratified)

[INFO] Training  â†’  Logistic_Regression ...
[INFO] 5-Fold CV ROC-AUC : 0.8884 Â± 0.0441

=======================================================
  Logistic_Regression  â€”  Evaluation Results
=======================================================
  accuracy    : 0.8689
  precision   : 0.8125
  recall      : 0.9286
  f1_score    : 0.8667
  roc_auc     : 0.9513

              precision    recall  f1-score   support

  No Disease       0.93      0.82      0.87        33
     Disease       0.81      0.93      0.87        28

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.88      0.87      0.87        61

[INFO] MLflow run ID : af4cda775e6e4a2aad1fa8a303f80444

[INFO] Training  â†’  Random_Forest ...
[INFO] 5-Fold CV ROC-AUC : 0.8882 Â± 0.0380

=======================================================
  Random_Forest  â€”  Evaluation Results
=======================================================
  accuracy    : 0.918
  precision   : 0.871
  recall      : 0.9643
  f1_score    : 0.9153
  roc_auc     : 0.9491

              precision    recall  f1-score   support

  No Disease       0.97      0.88      0.92        33
     Disease       0.87      0.96      0.92        28

    accuracy                           0.92        61
   macro avg       0.92      0.92      0.92        61
weighted avg       0.92      0.92      0.92        61

[INFO] MLflow run ID : 4403690371694023a3bef9db3259f7bc

=======================================================
  MODEL COMPARISON
=======================================================
  Logistic Regression  ROC-AUC : 0.9513
  Random Forest        ROC-AUC : 0.9491

  âœ…  Best model selected : Logistic_Regression
      ROC-AUC             : 0.9513
      Accuracy            : 0.8689

[INFO] Best model saved â†’ models\best_model.pkl

[DONE] Training complete.
[INFO] Run  'mlflow ui'  and open http://localhost:5000

2026/05/10 10:46:06 INFO mlflow.tracking.fluent: Experiment with name 'Heart_Disease_Classification' does not exist. Creating a new experiment.
2026/05/10 10:46:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/10 10:46:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Successfully registered model 'Logistic_Regression'.
Created version '1' of model 'Logistic_Regression'.
2026/05/10 10:46:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/10 10:46:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Successfully registered model 'Random_Forest'.
Created version '1' of model 'Random_Forest'.

#Verify Training Outputs

In [31]:
import os
import joblib

print("=" * 55)
print("  TRAINING OUTPUT VERIFICATION")
print("=" * 55)

# ── Check model files ─────────────────────────────────────
print("\n📦 Model Files:")
model_files = [
    "models/Logistic_Regression.pkl",
    "models/Random_Forest.pkl",
    "models/best_model.pkl",
]
for f in model_files:
    if os.path.exists(f):
        size = os.path.getsize(f)
        print(f"   ✅  {f}  ({size:,} bytes)")
    else:
        print(f"   ❌  {f}  — NOT FOUND")

# ── Check MLflow runs ─────────────────────────────────────
print("\n📊 MLflow Experiment Logs:")
if os.path.exists("mlruns"):
    print("   ✅  mlruns/ folder created")
    run_count = 0
    for root, dirs, files in os.walk("mlruns"):
        for d in dirs:
            if len(d) == 32:
                run_count += 1
    print(f"   ✅  {run_count} experiment run(s) logged")
else:
    print("   ❌  mlruns/ not found")

# ── Check screenshot files ────────────────────────────────
print("\n📈 Training Plot Screenshots:")
expected_plots = [
    "screenshots/cm_Logistic_Regression.png",
    "screenshots/cm_Random_Forest.png",
    "screenshots/roc_Logistic_Regression.png",
    "screenshots/roc_Random_Forest.png",
    "screenshots/feat_importance_Random_Forest.png",
]
for f in expected_plots:
    if os.path.exists(f):
        print(f"   ✅  {f}")
    else:
        print(f"   ⚠️   {f}  — not found")

print("\n" + "=" * 55)
print("  ✅  Verification Complete!")
print("=" * 55)

=======================================================
  TRAINING OUTPUT VERIFICATION
=======================================================

📦 Model Files:
   ✅  models/Logistic_Regression.pkl  (3,614 bytes)
   ✅  models/Random_Forest.pkl  (474,735 bytes)
   ✅  models/best_model.pkl  (3,614 bytes)

📊 MLflow Experiment Logs:
   ✅  mlruns/ folder created
   ✅  2 experiment run(s) logged

📈 Training Plot Screenshots:
   ✅  screenshots/cm_Logistic_Regression.png
   ✅  screenshots/cm_Random_Forest.png
   ✅  screenshots/roc_Logistic_Regression.png
   ✅  screenshots/roc_Random_Forest.png
   ✅  screenshots/feat_importance_Random_Forest.png

=======================================================
  ✅  Verification Complete!
=======================================================

#Load and Test Best Model created

In [32]:
import joblib
import pandas as pd
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"

# Load best model
model = joblib.load("models/best_model.pkl")

print("=" * 55)
print("  BEST MODEL INSPECTION")
print("=" * 55)

# Show pipeline steps
print("\n🔧 Pipeline Steps:")
for step_name, step_obj in model.steps:
    print(f"   {step_name} → {type(step_obj).__name__}")

# Show classifier details
classifier = model.named_steps["classifier"]
print(f"\n🤖 Classifier : {type(classifier).__name__}")

# Quick test prediction
sample = pd.DataFrame([{
    "age": 63, "sex": 1, "cp": 3,
    "trestbps": 145, "chol": 233, "fbs": 1,
    "restecg": 0, "thalach": 150, "exang": 0,
    "oldpeak": 2.3, "slope": 0, "ca": 0, "thal": 1
}])

prediction  = model.predict(sample)[0]
probability = model.predict_proba(sample)[0][1]

print(f"\n🧪 Quick Test Prediction:")
print(f"   Input      : 63yr Male, CP=3, Chol=233")
print(f"   Result     : {'✅ Disease' if prediction==1 else '✅ No Disease'}")
print(f"   Confidence : {probability:.4f} ({probability*100:.1f}%)")
print("\n✅ Model loaded and working correctly!")

=======================================================
  BEST MODEL INSPECTION
=======================================================

🔧 Pipeline Steps:
   preprocessor → ColumnTransformer
   classifier → LogisticRegression

🤖 Classifier : LogisticRegression

🧪 Quick Test Prediction:
   Input      : 63yr Male, CP=3, Chol=233
   Result     : ✅ No Disease
   Confidence : 0.0367 (3.7%)

✅ Model loaded and working correctly!

#Model Comparison

In [33]:
import joblib
import pandas as pd
import sys
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"
sys.path.insert(0, "src")

from preprocess import (
    load_data, clean_data,
    get_features_and_target, split_data
)
from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score
)

# Reload data with same split
df = load_data("data/heart_cleaned.csv")
df = clean_data(df)
X, y = get_features_and_target(df)
X_train, X_test, y_train, y_test = split_data(X, y)

# Compare both models
results = {}
for model_name, path in [
    ("Logistic Regression", "models/Logistic_Regression.pkl"),
    ("Random Forest",       "models/Random_Forest.pkl"),
]:
    m      = joblib.load(path)
    y_pred = m.predict(X_test)
    y_prob = m.predict_proba(X_test)[:, 1]

    results[model_name] = {
        "Accuracy"  : round(accuracy_score (y_test, y_pred), 4),
        "Precision" : round(precision_score(y_test, y_pred), 4),
        "Recall"    : round(recall_score   (y_test, y_pred), 4),
        "F1 Score"  : round(f1_score       (y_test, y_pred), 4),
        "ROC-AUC"   : round(roc_auc_score  (y_test, y_prob), 4),
    }

# Display comparison table
results_df = pd.DataFrame(results).T
print("=" * 55)
print("  FINAL MODEL COMPARISON TABLE")
print("=" * 55)
display(results_df)

# Best model
best = results_df["ROC-AUC"].idxmax()
print(f"\n  🏆  Best Model : {best}")
print(f"      ROC-AUC    : {results_df.loc[best, 'ROC-AUC']}")
print(f"      Accuracy   : {results_df.loc[best, 'Accuracy']}")
print(f"      Recall     : {results_df.loc[best, 'Recall']}")
print("=" * 55)

[INFO] Data loaded from 'data/heart_cleaned.csv' — shape: (303, 14)
[INFO] clean_data : no missing values detected.
[INFO] split_data  : train=242, test=61 (test_size=0.2, stratified)
=======================================================
  FINAL MODEL COMPARISON TABLE
=======================================================

                     Accuracy  Precision  Recall  F1 Score  ROC-AUC
Logistic Regression    0.8689     0.8125  0.9286    0.8667   0.9513
Random Forest          0.9180     0.8710  0.9643    0.9153   0.9491

  🏆  Best Model : Logistic Regression
      ROC-AUC    : 0.9513
      Accuracy   : 0.8689
      Recall     : 0.9286
=======================================================

#MLFlow UI Initialize

In [34]:
import subprocess
import sys
import time
import os
import socket

os.environ["GIT_PYTHON_REFRESH"] = "quiet"

# Kill any existing MLflow process first
subprocess.run(
    ["taskkill", "/F", "/IM", "python.exe"],
    capture_output=True
)
time.sleep(2)

# Try port 5001
mlflow_process = subprocess.Popen(
    [sys.executable, "-m", "mlflow", "ui",
     "--host", "127.0.0.1",
     "--port", "5001",
     "--backend-store-uri", "mlruns"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)

time.sleep(5)

# Check if it started
def is_port_in_use(port):
    with socket.socket(
        socket.AF_INET, socket.SOCK_STREAM
    ) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0

if is_port_in_use(5001):
    print("✅ MLflow UI started on port 5001!")
    print()
    print("  👉 Open browser and go to:")
    print("     http://127.0.0.1:5001")
else:
    print("❌ Port 5001 also not responding")
    print("   Trying to read error output...")
    try:
        stdout, stderr = mlflow_process.communicate(timeout=3)
        if stderr:
            print(f"   Error: {stderr.decode()}")
    except:
        pass

=======================================================
  STARTING MLFLOW UI
=======================================================
✅ MLflow UI started!

  👉 Open your browser and go to:
     http://127.0.0.1:5000

  📸 Take these 4 screenshots:
     1. Experiments list page
     2. Runs list (both models visible)
     3. Compare runs (metrics side by side)
     4. Random Forest run details page

  💾 Save screenshots to screenshots/ folder
=======================================================

#Since 5000 port is blocked, accessing MLFlow via python

In [2]:
import mlflow
import pandas as pd
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"

# Set tracking URI
mlflow.set_tracking_uri("mlruns")

print("=" * 55)
print("  MLFLOW EXPERIMENT RESULTS")
print("  (Viewed directly in notebook)")
print("=" * 55)

# Get experiment
experiment = mlflow.get_experiment_by_name(
    "Heart_Disease_Classification"
)

if experiment:
    print(f"\n✅ Experiment Found!")
    print(f"   Name       : {experiment.name}")
    print(f"   ID         : {experiment.experiment_id}")
    print(f"   Location   : {experiment.artifact_location}")

    # Get all runs
    runs = mlflow.search_runs(
        experiment_ids=[experiment.experiment_id],
        order_by=["metrics.roc_auc DESC"]
    )

    print(f"\n📊 All Runs ({len(runs)} total):")
    print("=" * 55)

    # Display key columns
    cols_to_show = [
        "tags.mlflow.runName",
        "metrics.accuracy",
        "metrics.precision",
        "metrics.recall",
        "metrics.f1_score",
        "metrics.roc_auc",
        "metrics.cv_roc_auc_mean",
    ]

    # Filter only existing columns
    cols_available = [
        c for c in cols_to_show
        if c in runs.columns
    ]

    display(runs[cols_available].round(4))

    print("\n🏆 Best Run by ROC-AUC:")
    best_run = runs.iloc[0]
    print(f"   Model    : {best_run.get('tags.mlflow.runName', 'N/A')}")
    print(f"   ROC-AUC  : {best_run.get('metrics.roc_auc', 'N/A'):.4f}")
    print(f"   Accuracy : {best_run.get('metrics.accuracy', 'N/A'):.4f}")
    print(f"   Run ID   : {best_run['run_id']}")

else:
    print("❌ Experiment not found!")
    print("   Make sure train.py ran successfully")

print("=" * 55)

=======================================================
  MLFLOW EXPERIMENT RESULTS
  (Viewed directly in notebook)
=======================================================

✅ Experiment Found!
   Name       : Heart_Disease_Classification
   ID         : 971894354608236588
   Location   : file:C:/Users/madhanma/OneDrive - Cisco/Github/MLOps/heart-disease-mlops/mlruns/971894354608236588

📊 All Runs (2 total):
=======================================================

C:\Users\madhanma\AppData\Roaming\Python\Python312\site-packages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)

,tags.mlflow.runName,metrics.accuracy,metrics.precision,metrics.recall,metrics.f1_score,metrics.roc_auc,metrics.cv_roc_auc_mean
0,Logistic_Regression,0.8689,0.8125,0.9286,0.8667,0.9513,0.8884
1,Random_Forest,0.9180,0.8710,0.9643,0.9153,0.9491,0.8882

🏆 Best Run by ROC-AUC:
   Model    : Logistic_Regression
   ROC-AUC  : 0.9513
   Accuracy : 0.8689
   Run ID   : af4cda775e6e4a2aad1fa8a303f80444
=======================================================

#Get MLFlow parameters

In [4]:
import mlflow
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"
mlflow.set_tracking_uri("mlruns")

experiment = mlflow.get_experiment_by_name(
    "Heart_Disease_Classification"
)
runs = mlflow.search_runs(
    experiment_ids=[experiment.experiment_id]
)

print("=" * 55)
print("  LOGGED PARAMETERS PER RUN")
print("=" * 55)

for _, run in runs.iterrows():
    run_id   = run["run_id"]
    run_name = run.get("tags.mlflow.runName", run_id[:8])

    print(f"\n📌 Run : {run_name}")
    print(f"   Run ID : {run_id[:16]}...")

    # Get full run details
    full_run = mlflow.get_run(run_id)
    params   = full_run.data.params
    metrics  = full_run.data.metrics

    print("   Parameters:")
    for k, v in params.items():
        print(f"     {k:<25} : {v}")

    print("   Metrics:")
    for k, v in metrics.items():
        print(f"     {k:<25} : {round(float(v), 4)}")

print("=" * 55)
print("✅ All MLflow data retrieved successfully!")
print()

=======================================================
  LOGGED PARAMETERS PER RUN
=======================================================

📌 Run : Random_Forest
   Run ID : 4403690371694023...
   Parameters:
     cv_folds                  : 5
     max_depth                 : 6
     min_samples_split         : 4
     model_name                : Random_Forest
     n_estimators              : 100
     n_features                : 13
     random_state              : 42
     test_samples              : 61
     train_samples             : 242
   Metrics:
     accuracy                  : 0.918
     cv_roc_auc_mean           : 0.8882
     cv_roc_auc_std            : 0.038
     f1_score                  : 0.9153
     precision                 : 0.871
     recall                    : 0.9643
     roc_auc                   : 0.9491

📌 Run : Logistic_Regression
   Run ID : af4cda775e6e4a2a...
   Parameters:
     C                         : 1.0
     cv_folds                  : 5
     max_iter                  : 1000
     model_name                : Logistic_Regression
     n_features                : 13
     random_state              : 42
     solver                    : lbfgs
     test_samples              : 61
     train_samples             : 242
   Metrics:
     accuracy                  : 0.8689
     cv_roc_auc_mean           : 0.8884
     cv_roc_auc_std            : 0.0441
     f1_score                  : 0.8667
     precision                 : 0.8125
     recall                    : 0.9286
     roc_auc                   : 0.9513
=======================================================
✅ All MLflow data retrieved successfully!

In [ ]:
#Preprocessing Tests

In [8]:
import sys
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"

print("=" * 55)
print("  RUNNING PREPROCESSING UNIT TESTS")
print("=" * 55)

!"{sys.executable}" -m pytest tests/test_preprocess.py \
    -v \
    --tb=short \
    --no-header

=======================================================
  RUNNING PREPROCESSING UNIT TESTS
=======================================================
============================= test session starts =============================
collecting ... collected 19 items

tests/test_preprocess.py::TestLoadData::test_raises_if_file_missing PASSED [  5%]
tests/test_preprocess.py::TestLoadData::test_loads_cleaned_csv_if_present PASSED [ 10%]
tests/test_preprocess.py::TestCleanData::test_no_nulls_remain_after_cleaning PASSED [ 15%]
tests/test_preprocess.py::TestCleanData::test_row_count_unchanged PASSED [ 21%]
tests/test_preprocess.py::TestCleanData::test_column_count_unchanged PASSED [ 26%]
tests/test_preprocess.py::TestCleanData::test_already_clean_df_passes_through PASSED [ 31%]
tests/test_preprocess.py::TestCleanData::test_fill_value_is_median PASSED [ 36%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_X_has_correct_number_of_columns PASSED [ 42%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_X_column_names_match_schema PASSED [ 47%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_y_is_binary PASSED [ 52%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_X_and_y_same_length PASSED [ 57%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_raises_on_missing_column PASSED [ 63%]
tests/test_preprocess.py::TestSplitData::test_total_size_preserved PASSED [ 68%]
tests/test_preprocess.py::TestSplitData::test_no_index_overlap PASSED    [ 73%]
tests/test_preprocess.py::TestSplitData::test_returns_four_objects PASSED [ 78%]
tests/test_preprocess.py::TestSplitData::test_reproducibility PASSED     [ 84%]
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_pipeline_instantiates PASSED [ 89%]
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape PASSED [ 94%]
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled PASSED [100%]

============================== warnings summary ===============================
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled
  C:\Users\madhanma\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
  See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
    return np.find_common_type(types, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================= 19 passed, 6 warnings in 1.74s ========================

#Run Model Test

In [14]:
import sys
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"

print("=" * 55)
print("  RUNNING MODEL UNIT TESTS")
print("=" * 55)

!"{sys.executable}" -m pytest tests/test_model.py \
    -v \
    --tb=short \
    --no-header

=======================================================
  RUNNING MODEL UNIT TESTS
=======================================================
============================= test session starts =============================
collecting ... collected 16 items

tests/test_model.py::TestModelFile::test_best_model_exists PASSED        [  6%]
tests/test_model.py::TestModelFile::test_model_is_loadable PASSED        [ 12%]
tests/test_model.py::TestModelPrediction::test_predict_returns_array PASSED [ 18%]
tests/test_model.py::TestModelPrediction::test_predict_single_value PASSED [ 25%]
tests/test_model.py::TestModelPrediction::test_prediction_is_binary PASSED [ 31%]
tests/test_model.py::TestModelPrediction::test_predict_proba_shape PASSED [ 37%]
tests/test_model.py::TestModelPrediction::test_probabilities_sum_to_one PASSED [ 43%]
tests/test_model.py::TestModelPrediction::test_probabilities_in_range PASSED [ 50%]
tests/test_model.py::TestModelPrediction::test_batch_prediction PASSED   [ 56%]
tests/test_model.py::TestModelPrediction::test_all_predictions_binary_in_batch PASSED [ 62%]
tests/test_model.py::TestPredictEndpoint::test_root_returns_200 PASSED   [ 68%]
tests/test_model.py::TestPredictEndpoint::test_health_endpoint PASSED    [ 75%]
tests/test_model.py::TestPredictEndpoint::test_predict_endpoint_returns_200 PASSED [ 81%]
tests/test_model.py::TestPredictEndpoint::test_predict_response_schema PASSED [ 87%]
tests/test_model.py::TestPredictEndpoint::test_predict_invalid_input_returns_422 PASSED [ 93%]
tests/test_model.py::TestPredictEndpoint::test_metrics_endpoint PASSED   [100%]

============================== warnings summary ===============================
tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:104: DeprecationWarning:
          on_event is deprecated, use lifespan event handlers instead.

          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

    @app.on_event("startup")

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\AppData\Roaming\Python\Python312\site-packages\fastapi\applications.py:4598: DeprecationWarning:
          on_event is deprecated, use lifespan event handlers instead.

          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

    return self.router.on_event(event_type)  # ty: ignore[deprecated]

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:132: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    age      : float = Field(..., ge=1,  le=120, example=63,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:134: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    sex      : float = Field(..., ge=0,  le=1,   example=1,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:136: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    cp       : float = Field(..., ge=0,  le=3,   example=3,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:138: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    trestbps : float = Field(..., ge=80, le=250,  example=145,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:140: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    chol     : float = Field(..., ge=100, le=600, example=233,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:142: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    fbs      : float = Field(..., ge=0,  le=1,   example=1,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:144: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    restecg  : float = Field(..., ge=0,  le=2,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:146: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    thalach  : float = Field(..., ge=60, le=250,  example=150,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:148: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    exang    : float = Field(..., ge=0,  le=1,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:150: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    oldpeak  : float = Field(..., ge=0,  le=10,  example=2.3,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:152: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    slope    : float = Field(..., ge=0,  le=2,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:154: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    ca       : float = Field(..., ge=0,  le=4,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:156: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    thal     : float = Field(..., ge=0,  le=3,   example=1,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\src\app.py:127: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    class PatientData(BaseModel):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================= 16 passed, 16 warnings in 2.96s =======================

#Run Complete Test Suite

In [15]:
import sys
import os

os.environ["GIT_PYTHON_REFRESH"] = "quiet"
os.environ["MODEL_PATH"] = os.path.abspath(
    "models/best_model.pkl"
)

print("=" * 55)
print("  COMPLETE TEST SUITE — ALL TESTS")
print("=" * 55)

!"{sys.executable}" -m pytest tests/ \
    -v \
    --tb=short \
    --no-header

print()

=======================================================
  COMPLETE TEST SUITE — ALL TESTS
=======================================================
============================= test session starts =============================
collecting ... collected 35 items

tests/test_model.py::TestModelFile::test_best_model_exists PASSED        [  2%]
tests/test_model.py::TestModelFile::test_model_is_loadable PASSED        [  5%]
tests/test_model.py::TestModelPrediction::test_predict_returns_array PASSED [  8%]
tests/test_model.py::TestModelPrediction::test_predict_single_value PASSED [ 11%]
tests/test_model.py::TestModelPrediction::test_prediction_is_binary PASSED [ 14%]
tests/test_model.py::TestModelPrediction::test_predict_proba_shape PASSED [ 17%]
tests/test_model.py::TestModelPrediction::test_probabilities_sum_to_one PASSED [ 20%]
tests/test_model.py::TestModelPrediction::test_probabilities_in_range PASSED [ 22%]
tests/test_model.py::TestModelPrediction::test_batch_prediction PASSED   [ 25%]
tests/test_model.py::TestModelPrediction::test_all_predictions_binary_in_batch PASSED [ 28%]
tests/test_model.py::TestPredictEndpoint::test_root_returns_200 PASSED   [ 31%]
tests/test_model.py::TestPredictEndpoint::test_health_endpoint PASSED    [ 34%]
tests/test_model.py::TestPredictEndpoint::test_predict_endpoint_returns_200 PASSED [ 37%]
tests/test_model.py::TestPredictEndpoint::test_predict_response_schema PASSED [ 40%]
tests/test_model.py::TestPredictEndpoint::test_predict_invalid_input_returns_422 PASSED [ 42%]
tests/test_model.py::TestPredictEndpoint::test_metrics_endpoint PASSED   [ 45%]
tests/test_preprocess.py::TestLoadData::test_raises_if_file_missing PASSED [ 48%]
tests/test_preprocess.py::TestLoadData::test_loads_cleaned_csv_if_present PASSED [ 51%]
tests/test_preprocess.py::TestCleanData::test_no_nulls_remain_after_cleaning PASSED [ 54%]
tests/test_preprocess.py::TestCleanData::test_row_count_unchanged PASSED [ 57%]
tests/test_preprocess.py::TestCleanData::test_column_count_unchanged PASSED [ 60%]
tests/test_preprocess.py::TestCleanData::test_already_clean_df_passes_through PASSED [ 62%]
tests/test_preprocess.py::TestCleanData::test_fill_value_is_median PASSED [ 65%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_X_has_correct_number_of_columns PASSED [ 68%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_X_column_names_match_schema PASSED [ 71%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_y_is_binary PASSED [ 74%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_X_and_y_same_length PASSED [ 77%]
tests/test_preprocess.py::TestGetFeaturesAndTarget::test_raises_on_missing_column PASSED [ 80%]
tests/test_preprocess.py::TestSplitData::test_total_size_preserved PASSED [ 82%]
tests/test_preprocess.py::TestSplitData::test_no_index_overlap PASSED    [ 85%]
tests/test_preprocess.py::TestSplitData::test_returns_four_objects PASSED [ 88%]
tests/test_preprocess.py::TestSplitData::test_reproducibility PASSED     [ 91%]
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_pipeline_instantiates PASSED [ 94%]
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape PASSED [ 97%]
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled PASSED [100%]

============================== warnings summary ===============================
tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:104: DeprecationWarning:
          on_event is deprecated, use lifespan event handlers instead.

          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

    @app.on_event("startup")

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\AppData\Roaming\Python\Python312\site-packages\fastapi\applications.py:4598: DeprecationWarning:
          on_event is deprecated, use lifespan event handlers instead.

          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

    return self.router.on_event(event_type)  # ty: ignore[deprecated]

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:132: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    age      : float = Field(..., ge=1,  le=120, example=63,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:134: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    sex      : float = Field(..., ge=0,  le=1,   example=1,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:136: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    cp       : float = Field(..., ge=0,  le=3,   example=3,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:138: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    trestbps : float = Field(..., ge=80, le=250,  example=145,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:140: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    chol     : float = Field(..., ge=100, le=600, example=233,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:142: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    fbs      : float = Field(..., ge=0,  le=1,   example=1,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:144: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    restecg  : float = Field(..., ge=0,  le=2,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:146: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    thalach  : float = Field(..., ge=60, le=250,  example=150,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:148: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    exang    : float = Field(..., ge=0,  le=1,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:150: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    oldpeak  : float = Field(..., ge=0,  le=10,  example=2.3,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:152: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    slope    : float = Field(..., ge=0,  le=2,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:154: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    ca       : float = Field(..., ge=0,  le=4,   example=0,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:156: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    thal     : float = Field(..., ge=0,  le=3,   example=1,

tests/test_model.py::TestPredictEndpoint::test_root_returns_200
  C:\Users\madhanma\OneDrive - Cisco\Github\MLOps\heart-disease-mlops\tests\..\src\app.py:127: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.13/migration/
    class PatientData(BaseModel):

tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_fit_transform_shape
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled
tests/test_preprocess.py::TestBuildPreprocessingPipeline::test_numerical_columns_are_scaled
  C:\Users\madhanma\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
  See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
    return np.find_common_type(types, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================= 35 passed, 22 warnings in 1.61s =======================

In [ ]:
#Checking Docker is Ready

In [18]:
import subprocess
import sys
import os

print("=" * 55)
print("  DOCKER DESKTOP VERIFICATION")
print("=" * 55)

# Check Docker version
result = subprocess.run(
    ["docker", "--version"],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print(f"  ✅  Docker found!")
    print(f"      {result.stdout.strip()}")
else:
    print(f"  ❌  Docker not found!")
    print(f"      Make sure Docker Desktop is running")
    print(f"      Look for Docker icon in system tray")

# Check Docker is actually running (not just installed)
result2 = subprocess.run(
    ["docker", "info"],
    capture_output=True,
    text=True
)

if result2.returncode == 0:
    print(f"\n  ✅  Docker Engine is running!")
else:
    print(f"\n  ❌  Docker Engine is NOT running!")
    print(f"      Please open Docker Desktop")
    print(f"      Wait for it to fully start")
    print(f"      (Green icon in system tray)")

# Check Docker Compose
result3 = subprocess.run(
    ["docker", "compose", "version"],
    capture_output=True,
    text=True
)
if result3.returncode == 0:
    print(f"\n  ✅  Docker Compose found!")
    print(f"      {result3.stdout.strip()}")
else:
    print(f"\n  ⚠️   Docker Compose not found")
    print(f"      (Will handle this later)")

print("=" * 55)

=======================================================
  DOCKER DESKTOP VERIFICATION
=======================================================
  ✅  Docker found!
      Docker version 29.4.2, build 055a478

  ✅  Docker Engine is running!

  ✅  Docker Compose found!
      Docker Compose version v5.1.3
=======================================================

#Verify Dockerfile & Files Exists

In [19]:
import os

print("=" * 55)
print("  PRE-BUILD VERIFICATION")
print("=" * 55)

# Check all files needed for Docker build
required_files = [
    "Dockerfile",
    "requirements.txt",
    "src/app.py",
    "src/preprocess.py",
    "models/best_model.pkl",
]

all_good = True
print("\n📋 Required Files:")
for f in required_files:
    exists = os.path.exists(f)
    size   = os.path.getsize(f) if exists else 0
    status = "✅" if exists else "❌"
    print(f"  {status}  {f:<35} {size:>10,} bytes")
    if not exists:
        all_good = False

print()
if all_good:
    print("  ✅  All files present — Ready to build!")
else:
    print("  ❌  Some files missing — Fix before building!")

print("=" * 55)

=======================================================
  PRE-BUILD VERIFICATION
=======================================================

📋 Required Files:
  ✅  Dockerfile                               3,089 bytes
  ✅  requirements.txt                         1,854 bytes
  ✅  src/app.py                              12,213 bytes
  ✅  src/preprocess.py                        9,473 bytes
  ✅  models/best_model.pkl                    3,614 bytes

  ✅  All files present — Ready to build!
=======================================================

#Build Docker Image

In [45]:
import subprocess
import sys
import os

print("=" * 55)
print("  BUILDING DOCKER IMAGE")
print("  heart-disease-api:v1")
print("=" * 55)
print()
print("  ⏳ This takes 3-8 minutes first time...")
print("     (Downloading Python base image)")
print()

# Build the image
result = subprocess.run(
    [
        "docker", "build",
        "--tag", "heart-disease-api:v1",
        "--no-cache",
        "."
    ],
    capture_output=False,  # Show output live
    text=True,
    cwd=os.getcwd()        # Build from project root
)

print()
print("=" * 55)
if result.returncode == 0:
    print("  ✅  Docker image built successfully!")
    print("      Image: heart-disease-api:v1")
else:
    print("  ❌  Docker build failed!")
    print(f"      Return code: {result.returncode}")
print("=" * 55)

=======================================================
  BUILDING DOCKER IMAGE
  heart-disease-api:v1
=======================================================

  ⏳ This takes 3-8 minutes first time...
     (Downloading Python base image)


=======================================================
  ✅  Docker image built successfully!
      Image: heart-disease-api:v1
=======================================================

#Verifying Docker Image

In [47]:
import subprocess

print("=" * 55)
print("  DOCKER IMAGE VERIFICATION")
print("=" * 55)

result = subprocess.run(
    ["docker", "images", "heart-disease-api"],
    capture_output=True,
    text=True
)

print(result.stdout)

if "heart-disease-api" in result.stdout:
    print("  Image found in Docker!")
    print()
else:
    print("  Image NOT found!")

print("=" * 55)

=======================================================
  DOCKER IMAGE VERIFICATION
=======================================================
IMAGE                  ID             DISK USAGE   CONTENT SIZE   EXTRA
heart-disease-api:v1   08242a10903a       1.49GB          352MB

  Image found in Docker!

=======================================================

#Start Docker Container

In [48]:
import subprocess
import socket
import time

print("=" * 55)
print("  STARTING DOCKER CONTAINER")
print("=" * 55)

# Clean up any old container
subprocess.run(["docker", "stop", "heart-api"],
               capture_output=True)
subprocess.run(["docker", "rm",   "heart-api"],
               capture_output=True)
time.sleep(2)
print("  Cleaned up old containers")

# Start fresh container
result = subprocess.run(
    [
        "docker", "run",
        "--detach",
        "--publish", "8000:8000",
        "--name", "heart-api",
        "--env",
        "MODEL_PATH=/app/models/best_model.pkl",
        "--env", "PYTHONUNBUFFERED=1",
        "heart-disease-api:v1"
    ],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print(f"  Container started!")
    print(f"  ID : {result.stdout.strip()[:12]}...")
    print(f"  Name : heart-api")
    print(f"  Port : 8000 -> 8000")
else:
    print(f"  Failed to start!")
    print(f"  Error: {result.stderr}")

# Watch live logs while waiting
print("\n  Live logs while initializing:\n")
print("-" * 55)

ready = False
for i in range(10):
    time.sleep(5)
    elapsed = (i + 1) * 5

    # Get latest logs
    logs = subprocess.run(
        ["docker", "logs", "heart-api",
         "--tail", "4"],
        capture_output=True, text=True
    )
    log_text = (
        logs.stdout + logs.stderr
    ).strip()

    print(f"  [{elapsed:>2}s] {log_text[:80]}")

    # Check for success
    if "startup complete" in log_text.lower():
        print(f"\n  App started successfully!")
        ready = True
        break

    # Check for errors
    if "error" in log_text.lower():
        print(f"\n  Error in logs!")
        full_logs = subprocess.run(
            ["docker", "logs", "heart-api"],
            capture_output=True, text=True
        )
        print(full_logs.stdout)
        print(full_logs.stderr)
        break

    # Check port
    with socket.socket(
        socket.AF_INET, socket.SOCK_STREAM
    ) as s:
        s.settimeout(2)
        if s.connect_ex(("127.0.0.1", 8000)) == 0:
            print(f"\n  Port 8000 OPEN after {elapsed}s!")
            ready = True
            break

print("-" * 55)
if ready:
    print("\n  Container is READY!")
    print("  API available at: http://localhost:8000")
else:
    print("\n  Still starting — run next cell")

print("=" * 55)

=======================================================
  STARTING DOCKER CONTAINER
=======================================================
  Cleaned up old containers
  Container started!
  ID : b32037673627...
  Name : heart-api
  Port : 8000 -> 8000

  Live logs while initializing:

-------------------------------------------------------
  [ 5s] INFO:     127.0.0.1:58584 - "GET /health HTTP/1.1" 200 OK
2026-05-10 07:41:59,70

  App started successfully!
-------------------------------------------------------

  Container is READY!
  API available at: http://localhost:8000
=======================================================

#Test Running Container

In [50]:
import urllib.request
import json
import socket

print("=" * 55)
print("  API ENDPOINT TESTING")
print("=" * 55)

# Helper function
def test_get(url, label):
    print(f"\n  {label}")
    print(f"  GET {url}")
    try:
        with urllib.request.urlopen(
            url, timeout=10
        ) as r:
            data = json.loads(r.read())
            print(f"  Status : 200 OK")
            print(f"  Response: {data}")
            return True
    except Exception as e:
        print(f"  FAILED: {e}")
        return False

def test_post(url, payload, label):
    print(f"\n  {label}")
    print(f"  POST {url}")
    try:
        data = json.dumps(payload).encode("utf-8")
        req  = urllib.request.Request(
            url,
            data    = data,
            headers = {
                "Content-Type": "application/json"
            },
            method = "POST"
        )
        with urllib.request.urlopen(
            req, timeout=10
        ) as r:
            result = json.loads(r.read())
            print(f"  Status    : 200 OK")
            print(f"  Prediction: {result['prediction']}")
            print(f"  Diagnosis : {result['diagnosis']}")
            print(f"  Confidence: {result['confidence']}")
            print(f"  Risk Level: {result['risk_level']}")
            print(f"  Latency   : {result['latency_ms']}ms")
            return True
    except Exception as e:
        print(f"  FAILED: {e}")
        return False

# Run all tests
base = "http://localhost:8000"
results = {}

results["root"] = test_get(
    f"{base}/",
    "TEST 1: Root endpoint"
)

results["health"] = test_get(
    f"{base}/health",
    "TEST 2: Health endpoint"
)

results["predict"] = test_post(
    f"{base}/predict",
    {
        "age": 63, "sex": 1, "cp": 3,
        "trestbps": 145, "chol": 233,
        "fbs": 1, "restecg": 0,
        "thalach": 150, "exang": 0,
        "oldpeak": 2.3, "slope": 0,
        "ca": 0, "thal": 1
    },
    "TEST 3: Predict endpoint (High Risk Patient)"
)

results["predict2"] = test_post(
    f"{base}/predict",
    {
        "age": 35, "sex": 0, "cp": 1,
        "trestbps": 110, "chol": 180,
        "fbs": 0, "restecg": 0,
        "thalach": 185, "exang": 0,
        "oldpeak": 0.0, "slope": 2,
        "ca": 0, "thal": 2
    },
    "TEST 4: Predict endpoint (Low Risk Patient)"
)

# Test invalid input
print(f"\n  TEST 5: Invalid input (expect 422)")
try:
    data = json.dumps(
        {"age": 63}
    ).encode("utf-8")
    req  = urllib.request.Request(
        f"{base}/predict",
        data    = data,
        headers = {
            "Content-Type": "application/json"
        },
        method  = "POST"
    )
    urllib.request.urlopen(req, timeout=10)
    print("  FAILED: Should have returned 422")
    results["invalid"] = False
except urllib.error.HTTPError as e:
    if e.code == 422:
        print(f"  Status : 422 Unprocessable Entity")
        print(f"  Correctly rejected invalid input!")
        results["invalid"] = True
    else:
        print(f"  Got HTTP {e.code}")
        results["invalid"] = False

# Summary
print()
print("=" * 55)
print("  TEST SUMMARY")
print("=" * 55)
passed = 0
for test, result in results.items():
    icon = "PASS" if result else "FAIL"
    print(f"  [{icon}]  {test}")
    if result:
        passed += 1

print()
print(f"  {passed}/{len(results)} tests passed")
print()
print("=" * 55)

=======================================================
  API ENDPOINT TESTING
=======================================================

  TEST 1: Root endpoint
  GET http://localhost:8000/
  Status : 200 OK
  Response: {'status': 'healthy', 'service': 'Heart Disease Prediction API', 'version': '1.0.0'}

  TEST 2: Health endpoint
  GET http://localhost:8000/health
  Status : 200 OK
  Response: {'status': 'ok', 'model_loaded': True, 'model_path': '/app/models/best_model.pkl'}

  TEST 3: Predict endpoint (High Risk Patient)
  POST http://localhost:8000/predict
  Status    : 200 OK
  Prediction: 0
  Diagnosis : No Heart Disease Detected
  Confidence: 0.0367
  Risk Level: Low
  Latency   : 9.08ms

  TEST 4: Predict endpoint (Low Risk Patient)
  POST http://localhost:8000/predict
  Status    : 200 OK
  Prediction: 0
  Diagnosis : No Heart Disease Detected
  Confidence: 0.0064
  Risk Level: Low
  Latency   : 5.53ms

  TEST 5: Invalid input (expect 422)
  Status : 422 Unprocessable Entity
  Correctly rejected invalid input!

=======================================================
  TEST SUMMARY
=======================================================
  [PASS]  root
  [PASS]  health
  [PASS]  predict
  [PASS]  predict2
  [PASS]  invalid

  5/5 tests passed

=======================================================

#Check Container Logs

In [51]:
import subprocess

print("=" * 55)
print("  CONTAINER LOGS")
print("=" * 55)

result = subprocess.run(
    ["docker", "logs", "heart-api",
     "--tail", "30"],
    capture_output=True,
    text=True
)

print(result.stdout)
if result.stderr:
    print(result.stderr)

print()
print("=" * 55)

=======================================================
  CONTAINER LOGS
=======================================================
INFO:     127.0.0.1:58584 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:35840 - "GET /health HTTP/1.1" 200 OK
INFO:     172.17.0.1:50960 - "GET / HTTP/1.1" 200 OK
INFO:     172.17.0.1:50972 - "GET /health HTTP/1.1" 200 OK
INFO:     172.17.0.1:50978 - "POST /predict HTTP/1.1" 200 OK
INFO:     172.17.0.1:50994 - "POST /predict HTTP/1.1" 200 OK
INFO:     172.17.0.1:51004 - "POST /predict HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:44622 - "GET /health HTTP/1.1" 200 OK
INFO:     172.17.0.1:58318 - "GET / HTTP/1.1" 200 OK
INFO:     172.17.0.1:58334 - "GET /health HTTP/1.1" 200 OK
INFO:     172.17.0.1:58338 - "POST /predict HTTP/1.1" 200 OK
INFO:     172.17.0.1:58344 - "POST /predict HTTP/1.1" 200 OK
INFO:     172.17.0.1:58358 - "POST /predict HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:35580 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:39624 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:48658 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:43906 - "GET /health HTTP/1.1" 200 OK

INFO:     Started server process [1]
INFO:     Waiting for application startup.
2026-05-10 07:41:58,199 | INFO     | Loading model from: /app/models/best_model.pkl
2026-05-10 07:41:59,702 | INFO     | Model loaded successfully.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2026-05-10 07:42:59,387 | INFO     | GET /  â€” health check
2026-05-10 07:42:59,492 | INFO     | POST /predict | prediction=0 | confidence=0.0367 | risk=Low | latency=55.97ms
2026-05-10 07:42:59,538 | INFO     | POST /predict | prediction=0 | confidence=0.0064 | risk=Low | latency=21.45ms
2026-05-10 07:43:29,813 | INFO     | GET /  â€” health check
2026-05-10 07:43:29,842 | INFO     | POST /predict | prediction=0 | confidence=0.0367 | risk=Low | latency=9.08ms
2026-05-10 07:43:29,855 | INFO     | POST /predict | prediction=0 | confidence=0.0064 | risk=Low | latency=5.53ms


=======================================================

#Kubernetes Verification

In [54]:
import subprocess

print("=" * 55)
print("  KUBERNETES VERIFICATION")
print("=" * 55)

# Check kubectl is available
result = subprocess.run(
    ["kubectl", "version", "--client"],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("  kubectl found!")
    print(f"  {result.stdout.strip()[:60]}")
else:
    print("  kubectl not found in PATH!")
    print("  Adding Docker Desktop kubectl path...")

    import os
    # Docker Desktop kubectl locations
    kubectl_paths = [
        r"C:\Program Files\Docker\Docker\resources\bin",
        r"C:\ProgramData\DockerDesktop\version-bin",
    ]
    for p in kubectl_paths:
        if os.path.exists(p):
            os.environ["PATH"] = (
                p + ";" + os.environ["PATH"]
            )
            print(f"  Added: {p}")

    # Retry
    result = subprocess.run(
        ["kubectl", "version", "--client"],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print("  kubectl now working!")
    else:
        print("  Still not found!")
        print("  Check Docker Desktop settings")

print()

# Check cluster is running
result2 = subprocess.run(
    ["kubectl", "cluster-info"],
    capture_output=True,
    text=True
)

if result2.returncode == 0:
    print("  Kubernetes cluster info:")
    for line in result2.stdout.strip().split("\n"):
        print(f"  {line}")
    print()
    print("  Kubernetes is running!")
else:
    print("  Cluster not ready yet!")
    print("  Error:", result2.stderr[:100])
    print()
print("=" * 55)

=======================================================
  KUBERNETES VERIFICATION
=======================================================
  kubectl found!
  Client Version: v1.34.1
Kustomize Version: v5.7.1

  Kubernetes cluster info:
  Kubernetes control plane is running at https://127.0.0.1:54318
  CoreDNS is running at https://127.0.0.1:54318/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

  To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

  Kubernetes is running!
=======================================================

#Check Nodes & Context

In [56]:
import subprocess

print("=" * 55)
print("  KUBERNETES CLUSTER STATUS")
print("=" * 55)

# Get current context
r1 = subprocess.run(
    ["kubectl", "config",
     "current-context"],
    capture_output=True, text=True
)
print(f"\n  Current context:")
print(f"  {r1.stdout.strip()}")

# Get nodes
r2 = subprocess.run(
    ["kubectl", "get", "nodes"],
    capture_output=True, text=True
)
print(f"\n  Cluster nodes:")
print(r2.stdout)

# Get namespaces
r3 = subprocess.run(
    ["kubectl", "get", "namespaces"],
    capture_output=True, text=True
)
print(f"  Namespaces:")
print(r3.stdout)

print("=" * 55)
print("=" * 55)

=======================================================
  KUBERNETES CLUSTER STATUS
=======================================================

  Current context:
  docker-desktop

  Cluster nodes:
NAME                    STATUS   ROLES           AGE    VERSION
desktop-control-plane   Ready    control-plane   9m7s   v1.34.3

  Namespaces:
NAME                 STATUS   AGE
default              Active   9m8s
kube-node-lease      Active   9m8s
kube-public          Active   9m8s
kube-system          Active   9m8s
local-path-storage   Active   8m52s

=======================================================
=======================================================

#Verify Deployment Files

In [57]:
import os

print("=" * 55)
print("  DEPLOYMENT FILES CHECK")
print("=" * 55)

files = {
    "deployment/deployment.yaml" : "Kubernetes Deployment",
    "deployment/service.yaml"    : "Kubernetes Service",
}

for f, desc in files.items():
    if os.path.exists(f):
        size = os.path.getsize(f)
        print(f"  OK  {f}")
        print(f"        {desc} — {size} bytes")
        print()
        # Show content
        with open(f, "r") as fh:
            print(fh.read())
        print("-" * 55)
    else:
        print(f"  MISSING  {f}")

print("=" * 55)

=======================================================
  DEPLOYMENT FILES CHECK
=======================================================
  OK  deployment/deployment.yaml
        Kubernetes Deployment — 2597 bytes

# =============================================================
# Heart Disease MLOps Pipeline
# File    : deployment/deployment.yaml
# Purpose : Kubernetes Deployment manifest â€” runs 2 replicas
#           of the FastAPI container with health probes.
#
# Apply   : kubectl apply -f deployment/deployment.yaml
# Check   : kubectl get pods
# =============================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api
  namespace: default
  labels:
    app: heart-disease-api
    version: v1
    project: mlops-assignment
spec:
  # Run 2 replicas for basic availability
  replicas: 2

  selector:
    matchLabels:
      app: heart-disease-api

  template:
    metadata:
      labels:
        app: heart-disease-api
        version: v1
    spec:
      containers:
        - name: heart-disease-api
          # Use local image built by: docker build -t heart-disease-api:v1 .
          image: heart-disease-api:v1
          # Never pull from registry â€” use the locally built image
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            - name: MODEL_PATH
              value: "/app/models/best_model.pkl"
            - name: PYTHONUNBUFFERED
              value: "1"

          # â”€â”€ Resource limits â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          # â”€â”€ Readiness probe â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          # Pod only receives traffic once /health returns 200
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          # â”€â”€ Liveness probe â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          # Restart container if /health fails repeatedly
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3

      # Graceful shutdown â€” give app 30s to finish in-flight requests
      terminationGracePeriodSeconds: 30
-------------------------------------------------------
  OK  deployment/service.yaml
        Kubernetes Service — 1034 bytes

# =============================================================
# Heart Disease MLOps Pipeline
# File    : deployment/service.yaml
# Purpose : Kubernetes Service â€” exposes the Deployment via
#           a LoadBalancer on port 80 â†’ 8000.
#           On Docker Desktop Kubernetes, the external IP
#           will be 'localhost'.
#
# Apply   : kubectl apply -f deployment/service.yaml
# Check   : kubectl get services
# Access  : http://localhost/docs
# =============================================================

apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  namespace: default
  labels:
    app: heart-disease-api
    project: mlops-assignment
spec:
  # LoadBalancer exposes the service externally.
  # On Docker Desktop, this maps to localhost.
  type: LoadBalancer

  selector:
    app: heart-disease-api

  ports:
    - name: http
      protocol: TCP
      # External port users will call
      port: 80
      # Port the container listens on
      targetPort: 8000
-------------------------------------------------------
=======================================================

In [ ]:
#Deploy to Kubernetes

In [59]:
import subprocess
import time

print("=" * 55)
print("  DEPLOYING TO KUBERNETES")
print("=" * 55)

# Apply Deployment
print("\n  Applying Deployment...")
r1 = subprocess.run(
    ["kubectl", "apply",
     "-f", "deployment/deployment.yaml"],
    capture_output=True, text=True
)
if r1.returncode == 0:
    print(f"  {r1.stdout.strip()}")
else:
    print(f"  Error: {r1.stderr.strip()}")

# Apply Service
print("\n  Applying Service...")
r2 = subprocess.run(
    ["kubectl", "apply",
     "-f", "deployment/service.yaml"],
    capture_output=True, text=True
)
if r2.returncode == 0:
    print(f"  {r2.stdout.strip()}")
else:
    print(f"  Error: {r2.stderr.strip()}")

# Wait for pods to start
print("\n  Waiting for pods to start (30s)...")
time.sleep(10)

# Check deployment status
print("\n  Deployment status:")
r3 = subprocess.run(
    ["kubectl", "get", "deployment",
     "heart-disease-api"],
    capture_output=True, text=True
)
print(r3.stdout)

# Check pods
print("  Pod status:")
r4 = subprocess.run(
    ["kubectl", "get", "pods",
     "-l", "app=heart-disease-api"],
    capture_output=True, text=True
)
print(r4.stdout)

# Check service
print("  Service status:")
r5 = subprocess.run(
    ["kubectl", "get", "service",
     "heart-disease-service"],
    capture_output=True, text=True
)
print(r5.stdout)

print("=" * 55)
print("=" * 55)

=======================================================
  DEPLOYING TO KUBERNETES
=======================================================

  Applying Deployment...
  deployment.apps/heart-disease-api unchanged

  Applying Service...
  service/heart-disease-service unchanged

  Waiting for pods to start (30s)...

  Deployment status:
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
heart-disease-api   0/2     2            0           49s

  Pod status:
NAME                                 READY   STATUS              RESTARTS   AGE
heart-disease-api-6d9bd578d4-fxjkz   0/1     ErrImageNeverPull   0          50s
heart-disease-api-6d9bd578d4-h8hfn   0/1     ErrImageNeverPull   0          50s

  Service status:
NAME                    TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
heart-disease-service   LoadBalancer   10.96.22.28   172.18.0.5    80:31789/TCP   50s

=======================================================
=======================================================

In [75]:
import subprocess
import os
import time

print("=" * 55)
print("  COMPLETE FIX — ONE SHOT")
print("=" * 55)

# Find Docker executable
r = subprocess.run(
    "where docker",
    shell=True,
    capture_output=True,
    text=True
)
docker_exe = r.stdout.strip().split("\n")[0].strip()
docker_dir = os.path.dirname(docker_exe)
os.environ["PATH"] = (
    docker_dir + ";" + os.environ["PATH"]
)
print(f"  Docker found : {docker_exe}")

# Step 1: Clean everything
print("\n  Step 1: Cleaning old deployment...")
subprocess.run(
    ["kubectl", "delete", "deployment",
     "heart-disease-api",
     "--ignore-not-found=true"],
    capture_output=True
)
subprocess.run(
    ["kubectl", "delete", "service",
     "heart-disease-service",
     "--ignore-not-found=true"],
    capture_output=True
)
time.sleep(5)
print("  Cleaned!")

# Step 2: Save image to tar
print("\n  Step 2: Saving image to tar file...")
r2 = subprocess.run(
    [
        "docker", "save",
        "heart-disease-api:v1",
        "-o", "heart-api.tar"
    ],
    capture_output=True, text=True,
    shell=False
)
if r2.returncode == 0:
    size = os.path.getsize("heart-api.tar")
    print(f"  Saved! Size: {size/1024/1024:.1f} MB")
else:
    print(f"  Error: {r2.stderr}")

print("=" * 55)

=======================================================
  COMPLETE FIX — ONE SHOT
=======================================================
  Docker found : C:\Program Files\Docker\Docker\resources\bin\docker

  Step 1: Cleaning old deployment...
  Cleaned!

  Step 2: Saving image to tar file...
  Saved! Size: 336.0 MB
=======================================================

In [81]:
import subprocess
import os
import time

print("=" * 55)
print("  DEPLOYING TO KUBERNETES")
print("=" * 55)

# Find Docker
r = subprocess.run(
    "where docker", shell=True,
    capture_output=True, text=True
)
docker_dir = os.path.dirname(
    r.stdout.strip().split("\n")[0].strip()
)
os.environ["PATH"] = (
    docker_dir + ";" + os.environ["PATH"]
)

# Clean old deployment
print("\n  Cleaning old deployment...")
subprocess.run(
    ["kubectl", "delete", "deployment",
     "heart-disease-api",
     "--ignore-not-found=true"],
    capture_output=True
)
subprocess.run(
    ["kubectl", "delete", "service",
     "heart-disease-service",
     "--ignore-not-found=true"],
    capture_output=True
)
time.sleep(5)
print("  Cleaned!")

# Write deployment manifest
deployment_yaml = """apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api
  namespace: default
  labels:
    app: heart-disease-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
        - name: heart-disease-api
          image: heart-disease-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "/app/models/best_model.pkl"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 15
            failureThreshold: 5
"""

service_yaml = """apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: heart-disease-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
"""

# Save manifests
with open("deployment/deployment.yaml",
          "w", encoding="utf-8") as f:
    f.write(deployment_yaml)

with open("deployment/service.yaml",
          "w", encoding="utf-8") as f:
    f.write(service_yaml)

print("\n  Manifests saved!")

# Apply
print("\n  Applying deployment...")
r1 = subprocess.run(
    ["kubectl", "apply",
     "-f", "deployment/deployment.yaml"],
    capture_output=True, text=True
)
print(f"  {r1.stdout.strip()}")
if r1.stderr:
    print(f"  Note: {r1.stderr.strip()[:100]}")

print("\n  Applying service...")
r2 = subprocess.run(
    ["kubectl", "apply",
     "-f", "deployment/service.yaml"],
    capture_output=True, text=True
)
print(f"  {r2.stdout.strip()}")

# Watch pods
print("\n  Watching pods (2 min max)...")
print("-" * 55)

success = False
for i in range(12):
    time.sleep(10)
    elapsed = (i + 1) * 10

    r = subprocess.run(
        ["kubectl", "get", "pods",
         "-l", "app=heart-disease-api"],
        capture_output=True, text=True
    )
    status = r.stdout.strip()
    print(f"\n  [{elapsed}s]")
    print(f"  {status}")

    # Success
    if "Running" in status:
        print("\n  Pod is RUNNING!")
        success = True

        # Get pod name
        pod_r = subprocess.run(
            ["kubectl", "get", "pods",
             "-l", "app=heart-disease-api",
             "-o", "name"],
            capture_output=True, text=True
        )
        pod = pod_r.stdout.strip().split("\n")[0]

        # Show logs
        logs = subprocess.run(
            ["kubectl", "logs",
             pod, "--tail", "10"],
            capture_output=True, text=True
        )
        print("\n  Pod logs:")
        print(logs.stdout)
        break

    # Still pulling
    if "Pending" in status or \
       "ContainerCreating" in status:
        print("  Still starting... keep waiting")
        continue

    # Image error
    if "ErrImage" in status:
        print("\n  Image error still!")
        pod_r = subprocess.run(
            ["kubectl", "get", "pods",
             "-l", "app=heart-disease-api",
             "-o", "name"],
            capture_output=True, text=True
        )
        pod = pod_r.stdout.strip().split("\n")[0]
        desc = subprocess.run(
            ["kubectl", "describe", pod],
            capture_output=True, text=True
        )
        if "Events:" in desc.stdout:
            print(desc.stdout[
                desc.stdout.find("Events:"):][:500]
            )
        break

    # Crash
    if "CrashLoop" in status:
        print("\n  CrashLoop!")
        pod_r = subprocess.run(
            ["kubectl", "get", "pods",
             "-l", "app=heart-disease-api",
             "-o", "name"],
            capture_output=True, text=True
        )
        pod = pod_r.stdout.strip().split("\n")[0]
        logs = subprocess.run(
            ["kubectl", "logs",
             pod, "--tail", "20"],
            capture_output=True, text=True
        )
        print(logs.stdout)
        print(logs.stderr)
        break

print("=" * 55)
if success:
    print("  DEPLOYMENT SUCCESSFUL!")
else:
    print("  Deployment needs attention")
    print("  Paste output above!")
print("=" * 55)

=======================================================
  DEPLOYING TO KUBERNETES
=======================================================

  Cleaning old deployment...
  Cleaned!

  Manifests saved!

  Applying deployment...
  deployment.apps/heart-disease-api created

  Applying service...
  service/heart-disease-service created

  Watching pods (2 min max)...
-------------------------------------------------------

  [10s]
  NAME                                 READY   STATUS    RESTARTS   AGE
heart-disease-api-7c5f7c5fcb-5b6n6   0/1     Running   0          13s

  Pod is RUNNING!

  Pod logs:
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2026-05-10 09:05:33,572 | INFO     | Loading model from: /app/models/best_model.pkl
2026-05-10 09:05:35,839 | INFO     | Model loaded successfully.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

=======================================================
  DEPLOYMENT SUCCESSFUL!
=======================================================

In [82]:
import urllib.request
import json
import subprocess

print("=" * 55)
print("  TESTING API VIA KUBERNETES")
print("=" * 55)

# Show service details first
r = subprocess.run(
    ["kubectl", "get", "service",
     "heart-disease-service"],
    capture_output=True, text=True
)
print("\n  Service details:")
print(r.stdout)

# Test endpoints
urls = [
    "http://localhost:30080",
    "http://localhost:80",
    "http://localhost:8000",
]

working = None
print("\n  Finding working URL...")
for url in urls:
    try:
        with urllib.request.urlopen(
            f"{url}/health", timeout=5
        ) as resp:
            data = json.loads(resp.read())
            print(f"\n  WORKING URL: {url}")
            print(f"  Response: {data}")
            working = url
            break
    except Exception as e:
        print(f"  {url} -> {str(e)[:50]}")

if working:
    # Test predict
    print(f"\n  Testing POST /predict...")
    payload = json.dumps({
        "age": 63, "sex": 1, "cp": 3,
        "trestbps": 145, "chol": 233,
        "fbs": 1, "restecg": 0,
        "thalach": 150, "exang": 0,
        "oldpeak": 2.3, "slope": 0,
        "ca": 0, "thal": 1
    }).encode("utf-8")

    req = urllib.request.Request(
        f"{working}/predict",
        data    = payload,
        headers = {
            "Content-Type": "application/json"
        },
        method  = "POST"
    )
    with urllib.request.urlopen(
        req, timeout=10
    ) as resp:
        result = json.loads(resp.read())
        print(f"  Prediction : {result['prediction']}")
        print(f"  Diagnosis  : {result['diagnosis']}")
        print(f"  Confidence : {result['confidence']}")
        print(f"  Risk       : {result['risk_level']}")

print("=" * 55)

=======================================================
  TESTING API VIA KUBERNETES
=======================================================

  Service details:
NAME                    TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
heart-disease-service   NodePort   10.96.169.166   <none>        80:30080/TCP   21s


  Finding working URL...
  http://localhost:30080 -> <urlopen error [WinError 10061] No connection coul
  http://localhost:80 -> <urlopen error [WinError 10061] No connection coul

  WORKING URL: http://localhost:8000
  Response: {'status': 'ok', 'model_loaded': True, 'model_path': '/app/models/best_model.pkl'}

  Testing POST /predict...
  Prediction : 0
  Diagnosis  : No Heart Disease Detected
  Confidence : 0.0367
  Risk       : Low
=======================================================

In [84]:
import subprocess

print("=" * 55)
print("  FULL KUBERNETES STATUS")
print("=" * 55)

commands = [
    (["kubectl", "get", "all",
      "-l", "app=heart-disease-api"],
     "All Resources"),
    (["kubectl", "get", "pods",
      "-l", "app=heart-disease-api",
      "-o", "wide"],
     "Pod Details"),
    (["kubectl", "get", "service",
      "heart-disease-service"],
     "Service Details"),
]

for cmd, label in commands:
    print(f"\n  {label}:")
    print("  " + "-" * 50)
    r = subprocess.run(
        cmd, capture_output=True, text=True
    )
    for line in r.stdout.strip().split("\n"):
        print(f"  {line}")

print()
print("=" * 55)
print("=" * 55)

=======================================================
  FULL KUBERNETES STATUS
=======================================================

  All Resources:
  --------------------------------------------------
  NAME                                     READY   STATUS    RESTARTS   AGE
  pod/heart-disease-api-7c5f7c5fcb-5b6n6   1/1     Running   0          47m

  NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
  deployment.apps/heart-disease-api   1/1     1            1           47m

  NAME                                           DESIRED   CURRENT   READY   AGE
  replicaset.apps/heart-disease-api-7c5f7c5fcb   1         1         1       47m

  Pod Details:
  --------------------------------------------------
  NAME                                 READY   STATUS    RESTARTS   AGE   IP           NODE                    NOMINATED NODE   READINESS GATES
  heart-disease-api-7c5f7c5fcb-5b6n6   1/1     Running   0          47m   10.244.0.9   desktop-control-plane   <none>           <none>

  Service Details:
  --------------------------------------------------
  NAME                    TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
  heart-disease-service   NodePort   10.96.169.166   <none>        80:30080/TCP   47m

=======================================================
=======================================================

#K8 Check Port & POD details

In [85]:
import subprocess
import socket
import os

print("=" * 55)
print("  PORT & POD DIAGNOSIS")
print("=" * 55)

# Find Docker
r = subprocess.run(
    "where docker", shell=True,
    capture_output=True, text=True
)
docker_dir = os.path.dirname(
    r.stdout.strip().split("\n")[0].strip()
)
os.environ["PATH"] = (
    docker_dir + ";" + os.environ["PATH"]
)

# Check pod status
print("\n  Pod status:")
r1 = subprocess.run(
    ["kubectl", "get", "pods",
     "-l", "app=heart-disease-api"],
    capture_output=True, text=True
)
print(r1.stdout)

# Check service
print("  Service status:")
r2 = subprocess.run(
    ["kubectl", "get", "service",
     "heart-disease-service"],
    capture_output=True, text=True
)
print(r2.stdout)

# Check ports
print("  Port check:")
for port in [30080, 8000, 80]:
    with socket.socket(
        socket.AF_INET, socket.SOCK_STREAM
    ) as s:
        s.settimeout(2)
        result = s.connect_ex(
            ("127.0.0.1", port)
        )
        status = "OPEN" if result == 0 else "CLOSED"
        print(f"  Port {port}: {status}")

print("=" * 55)

=======================================================
  PORT & POD DIAGNOSIS
=======================================================

  Pod status:
NAME                                 READY   STATUS    RESTARTS   AGE
heart-disease-api-7c5f7c5fcb-5b6n6   1/1     Running   0          49m

  Service status:
NAME                    TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
heart-disease-service   NodePort   10.96.169.166   <none>        80:30080/TCP   49m

  Port check:
  Port 30080: CLOSED
  Port 8000: OPEN
  Port 80: CLOSED
=======================================================

#K8 POD Logs

In [86]:
import subprocess

print("=" * 55)
print("  POD LOGS")
print("=" * 55)

# Get pod name
r = subprocess.run(
    ["kubectl", "get", "pods",
     "-l", "app=heart-disease-api",
     "-o", "name"],
    capture_output=True, text=True
)
pods = [
    p for p in r.stdout.strip().split("\n")
    if p.strip()
]

if pods:
    pod = pods[0]
    print(f"\n  Pod: {pod}")

    # Get logs
    logs = subprocess.run(
        ["kubectl", "logs",
         pod, "--tail", "20"],
        capture_output=True, text=True
    )
    print("\n  Logs:")
    print(logs.stdout)
    if logs.stderr:
        print("  Stderr:")
        print(logs.stderr)

    # Describe pod
    desc = subprocess.run(
        ["kubectl", "describe", pod],
        capture_output=True, text=True
    )
    # Show conditions & events
    out = desc.stdout
    if "Conditions:" in out:
        cond = out[out.find("Conditions:"):]
        print("\n  Conditions:")
        print(cond[:500])
    if "Events:" in out:
        events = out[out.find("Events:"):]
        print("\n  Events:")
        print(events[:500])
else:
    print("  No pods found!")

print("=" * 55)

=======================================================
  POD LOGS
=======================================================

  Pod: pod/heart-disease-api-7c5f7c5fcb-5b6n6

  Logs:
INFO:     10.244.0.1:38994 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:49032 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:49048 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:39290 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:39294 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:44976 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:37866 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:37882 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:39218 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:39222 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:55990 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:36188 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:36202 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:41592 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:41606 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:38670 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:50112 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:50116 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:34206 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:34210 - "GET /health HTTP/1.1" 200 OK


  Conditions:
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       True
  ContainersReady             True
  PodScheduled                True
Volumes:
  kube-api-access-w8x24:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:

  Events:
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  49m   default-scheduler  Successfully assigned default/heart-disease-api-7c5f7c5fcb-5b6n6 to desktop-control-plane
  Normal  Pulled     49m   kubelet            Container image "heart-disease-api:v1" already present on machine
  Normal  Created    49m   kubelet            Created container: heart-disease-api
  Normal  Started    49m   kubelet            Started
=======================================================

#K8 Portforward and Predict

In [ ]:
import subprocess
import time
import urllib.request
import json
import os

print("=" * 55)
print("  PORT FORWARD")
print("=" * 55)

# Fix PATH
extra_paths = [
    r"C:\Program Files\Docker\Docker\resources\bin",
    r"C:\ProgramData\DockerDesktop\version-bin",
]
for p in extra_paths:
    if os.path.exists(p):
        os.environ["PATH"] = (
            p + ";" + os.environ["PATH"]
        )

# Get pod name
r = subprocess.run(
    "kubectl get pods "
    "-l app=heart-disease-api -o name",
    shell=True,
    capture_output=True,
    text=True
)
pods = [
    p for p in r.stdout.strip().split("\n")
    if p.strip()
]

print(f"  Pods found: {pods}")

if not pods:
    print("  No pods! Check kubectl get pods")
else:
    pod = pods[0]
    print(f"  Using: {pod}")

    # Start port-forward
    pf = subprocess.Popen(
        f"kubectl port-forward {pod} 8080:8000",
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    print("  Waiting 10s...")
    time.sleep(10)

    if pf.poll() is not None:
        out, err = pf.communicate()
        print(f"  Failed!")
        print(f"  {err.decode()[:300]}")
    else:
        print("  Running!")

        # Test
        try:
            with urllib.request.urlopen(
                "http://localhost:8080/health",
                timeout=10
            ) as resp:
                data = json.loads(resp.read())
                print(f"\n  Health OK: {data}")
        except Exception as e:
            print(f"\n  Health error: {e}")

        try:
            payload = json.dumps({
                "age": 63, "sex": 1, "cp": 3,
                "trestbps": 145, "chol": 233,
                "fbs": 1, "restecg": 0,
                "thalach": 150, "exang": 0,
                "oldpeak": 2.3, "slope": 0,
                "ca": 0, "thal": 1
            }).encode("utf-8")
            req = urllib.request.Request(
                "http://localhost:8080/predict",
                data    = payload,
                headers = {
                    "Content-Type": "application/json"
                },
                method  = "POST"
            )
            with urllib.request.urlopen(
                req, timeout=10
            ) as resp:
                result = json.loads(resp.read())
                print(f"\n  Predict OK!")
                print(f"  Prediction : {result['prediction']}")
                print(f"  Diagnosis  : {result['diagnosis']}")
                print(f"  Confidence : {result['confidence']}")
                print(f"  Risk Level : {result['risk_level']}")
        except Exception as e:
            print(f"\n  Predict error: {e}")

        print()
        print("=" * 55)
        
        try:
            pf.wait()
        except KeyboardInterrupt:
            pf.terminate()
            print("  Stopped!")

print("=" * 55)

=======================================================
  PORT FORWARD
=======================================================
  Pods found: ['pod/heart-disease-api-7c5f7c5fcb-5b6n6']
  Using: pod/heart-disease-api-7c5f7c5fcb-5b6n6
  Waiting 10s...
  Running!

  Health OK: {'status': 'ok', 'model_loaded': True, 'model_path': '/app/models/best_model.pkl'}

  Predict OK!
  Prediction : 0
  Diagnosis  : No Heart Disease Detected
  Confidence : 0.0367
  Risk Level : Low

=======================================================

#Monitoring Stack using Prometheus & Grafana

In [2]:
import subprocess
import os
import time

print("=" * 55)
print("  STARTING MONITORING")
print("=" * 55)

# Step 1: Find Docker
print("\n  Finding Docker...")
r = subprocess.run(
    "where docker",
    shell=True,
    capture_output=True,
    text=True
)

if r.returncode == 0:
    docker_exe = (
        r.stdout.strip().split("\n")[0].strip()
    )
    docker_dir = os.path.dirname(docker_exe)
    os.environ["PATH"] = (
        docker_dir + ";" + os.environ["PATH"]
    )
    print(f"  Found: {docker_exe}")
else:
    # Manual common paths
    common = [
        r"C:\Program Files\Docker\Docker\resources\bin",
        r"C:\ProgramData\DockerDesktop\version-bin",
    ]
    for p in common:
        if os.path.exists(
            os.path.join(p, "docker.exe")
        ):
            os.environ["PATH"] = (
                p + ";" + os.environ["PATH"]
            )
            print(f"  Found at: {p}")
            break

# Verify Docker works
r2 = subprocess.run(
    "docker --version",
    shell=True,
    capture_output=True,
    text=True
)
if r2.returncode == 0:
    print(f"  Docker OK: {r2.stdout.strip()}")
else:
    print("  Docker still not found!")
    print("  Is Docker Desktop running?")

# Step 2: Check monitoring files
print("\n  Checking monitoring files...")
files = [
    "monitoring/docker-compose.yml",
    "monitoring/prometheus.yml",
]
all_ok = True
for f in files:
    if os.path.exists(f):
        print(f"  OK      {f}")
    else:
        print(f"  MISSING {f}")
        all_ok = False

# Step 3: Start monitoring stack
if all_ok:
    print("\n  Starting Prometheus + Grafana...")
    monitoring_dir = os.path.join(
        os.getcwd(), "monitoring"
    )

    r3 = subprocess.run(
        "docker compose up -d",
        shell=True,
        capture_output=True,
        text=True,
        cwd=monitoring_dir
    )

    if r3.returncode == 0:
        print("  Started successfully!")
        print(r3.stdout[-200:])
    else:
        # Try docker-compose (older syntax)
        print("  Trying docker-compose...")
        r4 = subprocess.run(
            "docker-compose up -d",
            shell=True,
            capture_output=True,
            text=True,
            cwd=monitoring_dir
        )
        if r4.returncode == 0:
            print("  Started with docker-compose!")
            print(r4.stdout[-200:])
        else:
            print(f"  Error: {r4.stderr[:300]}")
else:
    print("\n  Fix missing files first!")

print("=" * 55)

=======================================================
  STARTING MONITORING
=======================================================

  Finding Docker...
  Found at: C:\Program Files\Docker\Docker\resources\bin
  Docker OK: Docker version 29.4.2, build 055a478

  Checking monitoring files...
  OK      monitoring/docker-compose.yml
  OK      monitoring/prometheus.yml

  Starting Prometheus + Grafana...
  Started successfully!

=======================================================

In [ ]:
#Verify Monitoring Containers

In [3]:
import subprocess
import socket
import time
import os

print("=" * 55)
print("  MONITORING CONTAINERS STATUS")
print("=" * 55)

# Find Docker
r = subprocess.run(
    "where docker", shell=True,
    capture_output=True, text=True
)
docker_dir = os.path.dirname(
    r.stdout.strip().split("\n")[0].strip()
)
os.environ["PATH"] = (
    docker_dir + ";" + os.environ["PATH"]
)

# Wait for containers
print("\n  Waiting 30s for containers...")
time.sleep(30)

# Check containers
r = subprocess.run(
    "docker ps --filter name=prometheus "
    "--filter name=grafana "
    "--format table",
    shell=True,
    capture_output=True,
    text=True
)
print("\n  Running containers:")
print(r.stdout)

# Check ports
print("  Port status:")
for name, port in [
    ("Prometheus", 9090),
    ("Grafana",    3000),
    ("API",        8000),
]:
    with socket.socket(
        socket.AF_INET, socket.SOCK_STREAM
    ) as s:
        s.settimeout(3)
        result = s.connect_ex(("127.0.0.1", port))
        status = "OPEN" if result == 0 else "CLOSED"
        icon   = "OK" if result == 0 else "WAIT"
        print(f"  [{icon}]  {name:<12} "
              f"port {port}: {status}")

print()
print("=" * 55)
print("  URLs:")
print("  Prometheus : http://localhost:9090")
print("  Grafana    : http://localhost:3000")
print("               admin / admin")
print("=" * 55)

=======================================================
  MONITORING CONTAINERS STATUS
=======================================================

  Waiting 30s for containers...

  Running containers:
CONTAINER ID   IMAGE                     COMMAND                  CREATED              STATUS              PORTS                                         NAMES
e0d07f6cf77e   grafana/grafana:10.1.0    "/run.sh"                About a minute ago   Up About a minute   0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp   grafana
34a9250fbfa3   prom/prometheus:v2.47.0   "/bin/prometheus --câ€¦"   About a minute ago   Up About a minute   0.0.0.0:9090->9090/tcp, [::]:9090->9090/tcp   prometheus

  Port status:
  [OK]  Prometheus   port 9090: OPEN
  [OK]  Grafana      port 3000: OPEN
  [OK]  API          port 8000: OPEN

=======================================================
  URLs:
  Prometheus : http://localhost:9090
  Grafana    : http://localhost:3000
               admin / admin
=======================================================

In [ ]:
#Generate API Traffic for Metrics

In [4]:
import urllib.request
import json
import time
import random

print("=" * 55)
print("  GENERATING API TRAFFIC")
print("  For Prometheus metrics")
print("=" * 55)

# Sample patients
patients = [
    {
        "age": 63, "sex": 1, "cp": 3,
        "trestbps": 145, "chol": 233,
        "fbs": 1, "restecg": 0,
        "thalach": 150, "exang": 0,
        "oldpeak": 2.3, "slope": 0,
        "ca": 0, "thal": 1
    },
    {
        "age": 35, "sex": 0, "cp": 1,
        "trestbps": 110, "chol": 180,
        "fbs": 0, "restecg": 0,
        "thalach": 185, "exang": 0,
        "oldpeak": 0.0, "slope": 2,
        "ca": 0, "thal": 2
    },
    {
        "age": 55, "sex": 1, "cp": 2,
        "trestbps": 130, "chol": 250,
        "fbs": 0, "restecg": 1,
        "thalach": 160, "exang": 0,
        "oldpeak": 1.5, "slope": 1,
        "ca": 1, "thal": 2
    },
    {
        "age": 45, "sex": 0, "cp": 0,
        "trestbps": 120, "chol": 200,
        "fbs": 0, "restecg": 0,
        "thalach": 170, "exang": 0,
        "oldpeak": 0.5, "slope": 2,
        "ca": 0, "thal": 2
    },
]

# Send 20 requests
print("\n  Sending 20 requests to API...")
print("-" * 55)

success = 0
errors  = 0

for i in range(20):
    patient = patients[i % len(patients)]

    try:
        payload = json.dumps(patient).encode()
        req = urllib.request.Request(
            "http://localhost:8000/predict",
            data    = payload,
            headers = {
                "Content-Type": "application/json"
            },
            method  = "POST"
        )
        with urllib.request.urlopen(
            req, timeout=5
        ) as resp:
            result = json.loads(resp.read())
            success += 1
            print(
                f"  [{i+1:>2}] "
                f"Pred={result['prediction']} | "
                f"Risk={result['risk_level']:<6} | "
                f"{result['latency_ms']}ms"
            )
    except Exception as e:
        errors += 1
        print(f"  [{i+1:>2}] Error: {str(e)[:40]}")

    time.sleep(0.5)

print("-" * 55)
print(f"\n  Total   : 20 requests")
print(f"  Success : {success}")
print(f"  Errors  : {errors}")
print()
print("  Metrics now visible in Prometheus!")
print("=" * 55)

=======================================================
  GENERATING API TRAFFIC
  For Prometheus metrics
=======================================================

  Sending 20 requests to API...
-------------------------------------------------------
  [ 1] Pred=0 | Risk=Low    | 115.33ms
  [ 2] Pred=0 | Risk=Low    | 12.74ms
  [ 3] Pred=0 | Risk=Low    | 14.18ms
  [ 4] Pred=0 | Risk=Low    | 15.49ms
  [ 5] Pred=0 | Risk=Low    | 13.16ms
  [ 6] Pred=0 | Risk=Low    | 26.28ms
  [ 7] Pred=0 | Risk=Low    | 16.49ms
  [ 8] Pred=0 | Risk=Low    | 12.3ms
  [ 9] Pred=0 | Risk=Low    | 12.18ms
  [10] Pred=0 | Risk=Low    | 12.28ms
  [11] Pred=0 | Risk=Low    | 11.11ms
  [12] Pred=0 | Risk=Low    | 10.48ms
  [13] Pred=0 | Risk=Low    | 14.12ms
  [14] Pred=0 | Risk=Low    | 9.01ms
  [15] Pred=0 | Risk=Low    | 10.24ms
  [16] Pred=0 | Risk=Low    | 12.21ms
  [17] Pred=0 | Risk=Low    | 13.74ms
  [18] Pred=0 | Risk=Low    | 10.6ms
  [19] Pred=0 | Risk=Low    | 11.36ms
  [20] Pred=0 | Risk=Low    | 13.82ms
-------------------------------------------------------

  Total   : 20 requests
  Success : 20
  Errors  : 0

  Metrics now visible in Prometheus!
=======================================================

In [ ]:
#Verify Prometheus is Scraping

In [5]:
import urllib.request
import json
import time

print("=" * 55)
print("  PROMETHEUS VERIFICATION")
print("=" * 55)

time.sleep(5)

# Check Prometheus targets
print("\n  Checking Prometheus targets...")
try:
    with urllib.request.urlopen(
        "http://localhost:9090/api/v1/targets",
        timeout=10
    ) as resp:
        data = json.loads(resp.read())
        targets = data.get(
            "data", {}
        ).get("activeTargets", [])

        print(f"  Active targets: {len(targets)}")
        for t in targets:
            job    = t.get("labels", {}).get("job")
            health = t.get("health")
            url    = t.get(
                "scrapeUrl", ""
            )[:50]
            icon   = "OK" if health=="up" else "DOWN"
            print(f"  [{icon}]  {job:<25} {health}")
            print(f"        {url}")

except Exception as e:
    print(f"  Error: {e}")
    print("  Prometheus may still be starting")
    print("  Wait 30s and try again")

# Check our custom metrics
print("\n  Checking API metrics...")
try:
    with urllib.request.urlopen(
        "http://localhost:9090/api/v1/query"
        "?query=heart_api_requests_total",
        timeout=10
    ) as resp:
        data = json.loads(resp.read())
        results = data.get(
            "data", {}
        ).get("result", [])

        if results:
            val = results[0].get(
                "value", [0, 0]
            )[1]
            print(f"  Total requests: {val}")
            print("  Prometheus IS scraping API!")
        else:
            print("  Metric not found yet")
            print("  Wait 15s and refresh")

except Exception as e:
    print(f"  Query error: {e}")

print("=" * 55)

=======================================================
  PROMETHEUS VERIFICATION
=======================================================

  Checking Prometheus targets...
  Active targets: 2
  [OK]  heart-disease-api         up
        http://host.docker.internal:8000/metrics
  [OK]  prometheus                up
        http://localhost:9090/metrics

  Checking API metrics...
  Total requests: 30
  Prometheus IS scraping API!
=======================================================

In [ ]:
#Setup Grafana Dashboard

In [ ]:
print("=" * 55)
print("  GRAFANA SETUP GUIDE")
print("=" * 55)
print()
print("  Step 1: Open Grafana")
print("  URL: http://localhost:3000")
print("  User: admin")
print("  Pass: admin")
print("  (Click Skip when asked to change)")
print()
print("  Step 2: Add Prometheus datasource")
print("  Go to: Connections -> Data sources")
print("  Click: Add data source")
print("  Choose: Prometheus")
print("  URL: http://prometheus:9090")
print("  Click: Save & Test")
print("  Save: screenshots/grafana_datasource.png")
print()
print("  Step 3: Create Dashboard")
print("  Go to: Dashboards -> New Dashboard")
print("  Click: Add visualization")
print("  Select: Prometheus datasource")
print()
print("  Step 4: Add Panel 1 — Total Requests")
print("  Query: heart_api_requests_total")
print("  Title: Total API Requests")
print()
print("  Step 5: Add Panel 2 — Predictions")
print("  Query: heart_api_predictions_total")
print("  Title: Predictions by Class")
print()
print("  Step 6: Add Panel 3 — Latency")
print("  Query:")
print("  rate(heart_api_request_latency")
print("  _seconds_sum[5m])")
print("  Title: API Latency")
print()
print("  Step 7: Save dashboard")
print("  Name: Heart Disease API Monitor")
print("  Save: screenshots/grafana_dashboard.png")
print("=" * 55)

In [ ]:
#Monitoring SUmmary

In [ ]:
import subprocess
import os

print("=" * 55)
print("  MONITORING STACK SUMMARY")
print("=" * 55)

# Find Docker
r = subprocess.run(
    "where docker", shell=True,
    capture_output=True, text=True
)
docker_dir = os.path.dirname(
    r.stdout.strip().split("\n")[0].strip()
)
os.environ["PATH"] = (
    docker_dir + ";" + os.environ["PATH"]
)

# Show running containers
r = subprocess.run(
    "docker ps --format "
    "\"table {{.Names}}\\t"
    "{{.Status}}\\t{{.Ports}}\"",
    shell=True,
    capture_output=True,
    text=True
)
print("\n  Running containers:")
for line in r.stdout.strip().split("\n"):
    if any(x in line for x in [
        "prometheus", "grafana",
        "heart", "NAME"
    ]):
        print(f"  {line}")

print()
print("=" * 55)
print("  TASK 8 CHECKLIST")
print("=" * 55)
print()
checklist = [
    "Prometheus running at localhost:9090",
    "Grafana running at localhost:3000",
    "API metrics exposed at /metrics",
    "Prometheus scraping API metrics",
    "20 test requests sent to API",
    "Prometheus targets screenshot",
    "Prometheus metrics screenshot",
    "Grafana datasource configured",
    "Grafana dashboard created",
    "Grafana dashboard screenshot",
]
for i, item in enumerate(checklist, 1):
    print(f"  {i:>2}. [ ]  {item}")

print()
print("  Tick each as you complete!")
print("=" * 55)

In [ ]:
#Generate data for Grafana Charts

In [8]:
import urllib.request
import json
import time

print("=" * 55)
print("  GENERATING TRAFFIC FOR GRAFANA")
print("=" * 55)

patients = [
    {
        "age": 63, "sex": 1, "cp": 3,
        "trestbps": 145, "chol": 233,
        "fbs": 1, "restecg": 0,
        "thalach": 150, "exang": 0,
        "oldpeak": 2.3, "slope": 0,
        "ca": 0, "thal": 1
    },
    {
        "age": 35, "sex": 0, "cp": 1,
        "trestbps": 110, "chol": 180,
        "fbs": 0, "restecg": 0,
        "thalach": 185, "exang": 0,
        "oldpeak": 0.0, "slope": 2,
        "ca": 0, "thal": 2
    },
    {
        "age": 55, "sex": 1, "cp": 2,
        "trestbps": 130, "chol": 250,
        "fbs": 0, "restecg": 1,
        "thalach": 160, "exang": 0,
        "oldpeak": 1.5, "slope": 1,
        "ca": 1, "thal": 2
    },
]

print("\n  Sending 30 requests...")
print("-" * 55)

success = 0
for i in range(30):
    p = patients[i % len(patients)]
    try:
        payload = json.dumps(p).encode()
        req = urllib.request.Request(
            "http://localhost:8000/predict",
            data    = payload,
            headers = {
                "Content-Type": "application/json"
            },
            method  = "POST"
        )
        with urllib.request.urlopen(
            req, timeout=5
        ) as resp:
            r = json.loads(resp.read())
            success += 1
            if i % 5 == 0:
                print(
                    f"  [{i+1:>2}] "
                    f"pred={r['prediction']} "
                    f"risk={r['risk_level']}"
                )
    except Exception as e:
        print(f"  [{i+1:>2}] Error: {str(e)[:40]}")

    time.sleep(0.5)

print("-" * 55)
print(f"  Done! {success}/30 successful")
print()
print("=" * 55)

=======================================================
  GENERATING TRAFFIC FOR GRAFANA
=======================================================

  Sending 30 requests...
-------------------------------------------------------
  [ 1] pred=0 risk=Low
  [ 6] pred=0 risk=Low
  [11] pred=0 risk=Low
  [16] pred=0 risk=Low
  [21] pred=0 risk=Low
  [26] pred=0 risk=Low
-------------------------------------------------------
  Done! 30/30 successful

=======================================================

#Push to GIT

In [8]:
import subprocess
import os

print("=" * 55)
print("  INITIALIZE GIT REPOSITORY")
print("=" * 55)

GITHUB_USERNAME = "mmadhan21"
REPO_NAME       = "heart-disease-mlops"

REPO_URL = (
    f"https://github.com/"
    f"{GITHUB_USERNAME}/{REPO_NAME}.git"
)
print(f"  Repo URL: {REPO_URL}")

# Step 1: Initialize git
print("\n  Step 1: Initializing git...")
r1 = subprocess.run(
    "git init",
    shell=True,
    capture_output=True,
    text=True,
    cwd=os.getcwd()
)
print(f"  {r1.stdout.strip()}")

# Step 2: Add remote
print("\n  Step 2: Adding remote...")
# Remove existing remote if any
subprocess.run(
    "git remote remove origin",
    shell=True,
    capture_output=True
)
r2 = subprocess.run(
    f"git remote add origin {REPO_URL}",
    shell=True,
    capture_output=True,
    text=True
)
if r2.returncode == 0:
    print(f"  Remote added: {REPO_URL}")
else:
    print(f"  Error: {r2.stderr[:100]}")

# Step 3: Create .gitignore additions
extra_gitignore = (
    "\n# Extra ignores\n"
    "heart-api.tar\n"
    "*.tar\n"
    "mlops_env/\n"
    "__pycache__/\n"
    "*.pyc\n"
    ".ipynb_checkpoints/\n"
    "api_requests.log\n"
)
with open(".gitignore", "a",
          encoding="utf-8") as f:
    f.write(extra_gitignore)
print("\n  Step 3: .gitignore updated!")

# Step 4: Stage all files
print("\n  Step 4: Staging files...")
r4 = subprocess.run(
    "git add .",
    shell=True,
    capture_output=True,
    text=True
)
if r4.returncode == 0:
    print("  All files staged!")
else:
    print(f"  Error: {r4.stderr[:100]}")

# Step 5: Check what will be committed
r5 = subprocess.run(
    "git status --short",
    shell=True,
    capture_output=True,
    text=True
)
lines = r5.stdout.strip().split("\n")
print(f"\n  Files to commit: {len(lines)}")
for line in lines[:15]:
    print(f"  {line}")
if len(lines) > 15:
    print(f"  ... and {len(lines)-15} more")

print("=" * 55)

=======================================================
  INITIALIZE GIT REPOSITORY
=======================================================
  Repo URL: https://github.com/mmadhan21/heart-disease-mlops.git

  Step 1: Initializing git...
  Initialized empty Git repository in C:/Users/madhanma/OneDrive - Cisco/Github/MLOps/heart-disease-mlops/.git/

  Step 2: Adding remote...
  Remote added: https://github.com/mmadhan21/heart-disease-mlops.git

  Step 3: .gitignore updated!

  Step 4: Staging files...
  All files staged!

  Files to commit: 167
  A  .github/workflows/ci_cd.yml
  A  .gitignore
  A  00_MASTER_RUNNER.ipynb
  A  Dockerfile
  A  Readme.md
  A  Untitled.ipynb
  A  data/download_data.py
  A  data/heart_cleaned.csv
  A  data/heart_raw.csv
  A  deployment/deployment.yaml
  A  deployment/service.yaml
  A  mlruns/971894354608236588/4403690371694023a3bef9db3259f7bc/artifacts/Random_Forest.pkl
  A  mlruns/971894354608236588/4403690371694023a3bef9db3259f7bc/artifacts/cm_Random_Forest.png
  A  mlruns/971894354608236588/4403690371694023a3bef9db3259f7bc/artifacts/feat_importance_Random_Forest.png
  A  mlruns/971894354608236588/4403690371694023a3bef9db3259f7bc/artifacts/roc_Random_Forest.png
  ... and 152 more
=======================================================

In [ ]:
#Commit & Push

In [9]:
import subprocess
import os

print("=" * 55)
print("  COMMIT & PUSH TO GITHUB")
print("=" * 55)

GITHUB_USERNAME = "mmadhan21"

# Commit
print("\n  Committing...")
r1 = subprocess.run(
    'git commit -m '
    '"Initial commit: Heart Disease '
    'MLOps Pipeline - BITS Pilani WILP"',
    shell=True,
    capture_output=True,
    text=True
)
print(f"  {r1.stdout.strip()[:100]}")

# Set branch to main
print("\n  Setting branch to main...")
subprocess.run(
    "git branch -M main",
    shell=True,
    capture_output=True
)

# Push
print("\n  Pushing to GitHub...")
print("  (Browser will open for login)")
print("  OR enter credentials when prompted")
print()

r3 = subprocess.run(
    "git push -u origin main",
    shell=True,
    capture_output=False,
    text=True
)

if r3.returncode == 0:
    print()
    print("  Pushed successfully!")
    print()
    print("  Repo at:")
    print(f"  https://github.com/"
          f"{GITHUB_USERNAME}/"
          f"heart-disease-mlops")
else:
    print()
    print("  Push failed!")
print("=" * 55)

=======================================================
  COMMIT & PUSH TO GITHUB
=======================================================

  Committing...
  [main (root-commit) 52f96a6] Initial commit: Heart Disease MLOps Pipeline - BITS Pilani WILP
 167 fi

  Setting branch to main...

  Pushing to GitHub...
  (Browser will open for login)
  OR enter credentials when prompted


  Pushed successfully!

  Repo at:
  https://github.com/mmadhan21/heart-disease-mlops
=======================================================